//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationTermsAndConditionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationTermsAndConditionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Views.Registration.RegistrationTermsAndConditionsResources", typeof(RegistrationTermsAndConditionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read full terms and conditions of use.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The general purpose of the website is to provide access to web-based transactions and services relating to international waste shipments and to grant access to related data held by the Environment Agency (EA) in accordance with applicable legal provisions..
        /// </summary>
        public static string Terms1 {
            get {
                return ResourceManager.GetString("Terms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to, and use of any part of the website including text, and software are governed by these terms and conditions and using them constitutes acceptance of these terms and conditions by the user..
        /// </summary>
        public static string Terms2 {
            get {
                return ResourceManager.GetString("Terms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EA reserves the right to amend these terms and conditions at any time by posting amended terms and conditions on the website..
        /// </summary>
        public static string Terms3 {
            get {
                return ResourceManager.GetString("Terms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EA reserves the right to modify, limit or discontinue - in full or in part and without prior notice - the services and information available on the website at any time, to restrict access to the website and to deny, without notice, and at its sole discretion, any user&apos;s access to the website or any part thereof..
        /// </summary>
        public static string Terms4 {
            get {
                return ResourceManager.GetString("Terms4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users of the website must comply with all applicable laws and regulations. They must refrain from violating or attempting to violate the EA’s network security, and, in particular, from uploading or attaching viruses, corrupted files or any software that might damage the operation of these services..
        /// </summary>
        public static string Terms5 {
            get {
                return ResourceManager.GetString("Terms5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the services available on this website require registration. Users must provide correct and complete information when registering, and update it as necessary. They must not misuse any access rights granted to them (for example by transferring data to unauthorised third persons). By registering, users agree to being contacted by the EA by e‑mail..
        /// </summary>
        public static string Terms6 {
            get {
                return ResourceManager.GetString("Terms6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions of use.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered users are responsible for maintaining the confidentiality of their account and password to prevent unauthorised access to that account. Users must take all necessary steps to keep their password secure and must inform the EA without delay at needanappropriateemailaddress@ea.gov.uk if it is being or could be used without authorisation..
        /// </summary>
        public static string TermsListItem1 {
            get {
                return ResourceManager.GetString("TermsListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the event of any violation of the above user obligations, the EA is entitled to revoke the user&apos;s access rights without prior notice..
        /// </summary>
        public static string TermsListItem2 {
            get {
                return ResourceManager.GetString("TermsListItem2", resourceCulture);
            }
        }
    }
}
