//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationMovements.Views.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationMovements.Views.Create.SummaryResources", typeof(SummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete sections 7 and 8.
        /// </summary>
        public static string CompleteBlocks7And8 {
            get {
                return ResourceManager.GetString("CompleteBlocks7And8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your prenotification(s), you now need to:.
        /// </summary>
        public static string CompletePrenotificationsParagraph {
            get {
                return ResourceManager.GetString("CompletePrenotificationsParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new prenotification(s) for this notification.
        /// </summary>
        public static string CreateNewLink {
            get {
                return ResourceManager.GetString("CreateNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} your IWS movement document(s).
        /// </summary>
        public static string DownloadTheDocuments {
            get {
                return ResourceManager.GetString("DownloadTheDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification options.
        /// </summary>
        public static string NotificationOptions {
            get {
                return ResourceManager.GetString("NotificationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging type(s).
        /// </summary>
        public static string PackagingTypes {
            get {
                return ResourceManager.GetString("PackagingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the documents.
        /// </summary>
        public static string PrintTheDocuments {
            get {
                return ResourceManager.GetString("PrintTheDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment number(s).
        /// </summary>
        public static string ShipmentNumbers {
            get {
                return ResourceManager.GetString("ShipmentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign the completed documents.
        /// </summary>
        public static string SignIt {
            get {
                return ResourceManager.GetString("SignIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve created IWS movement documents for {0} shipments, totalling {1}..
        /// </summary>
        public static string SummaryParagraph {
            get {
                return ResourceManager.GetString("SummaryParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your prenotification(s).
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can {0} now, or do it later by visiting your {1} page..
        /// </summary>
        public static string UploadPrenotificationsParagraph {
            get {
                return ResourceManager.GetString("UploadPrenotificationsParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your signed documents.
        /// </summary>
        public static string UploadTheSignedDocuments {
            get {
                return ResourceManager.GetString("UploadTheSignedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload your signed documents.
        /// </summary>
        public static string UploadTheSignedFilesNow {
            get {
                return ResourceManager.GetString("UploadTheSignedFilesNow", resourceCulture);
            }
        }
    }
}
