//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminImportNotificationMovements.ViewModels.MovementOverride {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminImportNotificationMovements.ViewModels.MovementOverride.Ind" +
                            "exViewModelResources", typeof(IndexViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity received.
        /// </summary>
        public static string ActualQuantityLabel {
            get {
                return ResourceManager.GetString("ActualQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual date of shipment.
        /// </summary>
        public static string ActualShipmentDate {
            get {
                return ResourceManager.GetString("ActualShipmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the actual shipment date.
        /// </summary>
        public static string ActualShipmentDateRequired {
            get {
                return ResourceManager.GetString("ActualShipmentDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enter comments against this shipment?.
        /// </summary>
        public static string HasComments {
            get {
                return ResourceManager.GetString("HasComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prenotification received.
        /// </summary>
        public static string HasNoPrenotification {
            get {
                return ResourceManager.GetString("HasNoPrenotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment {0}.
        /// </summary>
        public static string NewShipmentNumber {
            get {
                return ResourceManager.GetString("NewShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenotification date.
        /// </summary>
        public static string PrenotificationDate {
            get {
                return ResourceManager.GetString("PrenotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tick the box or enter prenotification received date.
        /// </summary>
        public static string PrenotificationDateRequired {
            get {
                return ResourceManager.GetString("PrenotificationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the actual quantity.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the waste received?.
        /// </summary>
        public static string ReceivedDateLabel {
            get {
                return ResourceManager.GetString("ReceivedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the waste received?.
        /// </summary>
        public static string ReceivedDateLabel1 {
            get {
                return ResourceManager.GetString("ReceivedDateLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason why the shipment was rejected and any relevant details.
        /// </summary>
        public static string RejectionReasonLabel {
            get {
                return ResourceManager.GetString("RejectionReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a reason for rejection.
        /// </summary>
        public static string RejectReasonRequired {
            get {
                return ResourceManager.GetString("RejectReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment number.
        /// </summary>
        public static string ShipmentNumber {
            get {
                return ResourceManager.GetString("ShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSR/Basel annual stats marking (when required).
        /// </summary>
        public static string StatsMarking {
            get {
                return ResourceManager.GetString("StatsMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was the shipment accepted?.
        /// </summary>
        public static string WasShipmentAcceptedLabel {
            get {
                return ResourceManager.GetString("WasShipmentAcceptedLabel", resourceCulture);
            }
        }
    }
}
