//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Views.Applicant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Views.Applicant.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new notification based on a previous one.
        /// </summary>
        public static string CopyNotification {
            get {
                return ResourceManager.GetString("CopyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving notifications, please try again..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  first..
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string FullStop {
            get {
                return ResourceManager.GetString("FullStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated the following notifications.
        /// </summary>
        public static string GeneratedMessage {
            get {
                return ResourceManager.GetString("GeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your homepage.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account services.
        /// </summary>
        public static string HeaderAccountServices {
            get {
                return ResourceManager.GetString("HeaderAccountServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your notifications.
        /// </summary>
        public static string HeaderManageYourNotifications {
            get {
                return ResourceManager.GetString("HeaderManageYourNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to start a notification?.
        /// </summary>
        public static string HeaderStartNew {
            get {
                return ResourceManager.GetString("HeaderStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string LinkChoose {
            get {
                return ResourceManager.GetString("LinkChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no notifications..
        /// </summary>
        public static string MessageNoNotification {
            get {
                return ResourceManager.GetString("MessageNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link opens in a new browser tab.
        /// </summary>
        public static string NewBrowserMessage {
            get {
                return ResourceManager.GetString("NewBrowserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could also.
        /// </summary>
        public static string OrYouCan {
            get {
                return ResourceManager.GetString("OrYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer (site&amp;nbsp;of&amp;nbsp;export).
        /// </summary>
        public static string ProducerTableHeader {
            get {
                return ResourceManager.GetString("ProducerTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new notification now or read the .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new notification.
        /// </summary>
        public static string StartNewNotification {
            get {
                return ResourceManager.GetString("StartNewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supporting information.
        /// </summary>
        public static string SupportingInfo {
            get {
                return ResourceManager.GetString("SupportingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string TableCaption {
            get {
                return ResourceManager.GetString("TableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ThAction {
            get {
                return ResourceManager.GetString("ThAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter - notifier.
        /// </summary>
        public static string ThExporter {
            get {
                return ResourceManager.GetString("ThExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer - consignee.
        /// </summary>
        public static string ThImporter {
            get {
                return ResourceManager.GetString("ThImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification number.
        /// </summary>
        public static string ThNotificationNumber {
            get {
                return ResourceManager.GetString("ThNotificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ThStatus {
            get {
                return ResourceManager.GetString("ThStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status date.
        /// </summary>
        public static string ThStatusDate {
            get {
                return ResourceManager.GetString("ThStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Notifications.
        /// </summary>
        public static string TitleManageNotifications {
            get {
                return ResourceManager.GetString("TitleManageNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View supporting information on GOV.UK in new tab.
        /// </summary>
        public static string TitleSupportingInfo {
            get {
                return ResourceManager.GetString("TitleSupportingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
