//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationMovements.Views.ReceiptRecoveryBulkUpload {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptRecoveryBulkUploadResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptRecoveryBulkUploadResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationMovements.Views.ReceiptRecoveryBulkUpload.ReceiptRec" +
                            "overyBulkUploadResources", typeof(ReceiptRecoveryBulkUploadResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amend the actual date of shipment to be greater than three working days.
        /// </summary>
        public static string AmendActualDate {
            get {
                return ResourceManager.GetString("AmendActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must resolve all errors listed below before uploading your prenotification data again. If you experience further problems, contact askshipments@environment-agency.gov.uk for further advice..
        /// </summary>
        public static string ErrorsContactUs {
            get {
                return ResourceManager.GetString("ErrorsContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errors listed below are problems found during the validation of the .xlsx or. csv file content. These errors prevent the service from accepting your data, therefore all errors must be amended before attempting to re-upload your data..
        /// </summary>
        public static string ErrorsFileAdvice {
            get {
                return ResourceManager.GetString("ErrorsFileAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your prenotification data file contains {0} errors.
        /// </summary>
        public static string ErrorsHeaderText {
            get {
                return ResourceManager.GetString("ErrorsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk upload errors.
        /// </summary>
        public static string ErrorsTitle {
            get {
                return ResourceManager.GetString("ErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to notification options.
        /// </summary>
        public static string NotificationOptionsLink {
            get {
                return ResourceManager.GetString("NotificationOptionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the row of data from the data file and use the existing ‘generate a prenotification’ journey to inform us of these shipments.
        /// </summary>
        public static string RemoveShipment {
            get {
                return ResourceManager.GetString("RemoveShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to upload.
        /// </summary>
        public static string ReturnToUpload {
            get {
                return ResourceManager.GetString("ReturnToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying shipment movement documents.
        /// </summary>
        public static string ShipmentMovementDocumentHeader {
            get {
                return ResourceManager.GetString("ShipmentMovementDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the accompanying shipment movement documents for shipments:.
        /// </summary>
        public static string ShipmentMovementInstructions {
            get {
                return ResourceManager.GetString("ShipmentMovementInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no errors within the {filename} data file..
        /// </summary>
        public static string ShipmentMovementsSuccessText {
            get {
                return ResourceManager.GetString("ShipmentMovementsSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk upload of receipt and/or recovery data.
        /// </summary>
        public static string StartHeader {
            get {
                return ResourceManager.GetString("StartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload multiple receipt and/or recovery data and shipment movement documents to your notification..
        /// </summary>
        public static string StartText1 {
            get {
                return ResourceManager.GetString("StartText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to avoid any errors in your data..
        /// </summary>
        public static string StartText2 {
            get {
                return ResourceManager.GetString("StartText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave the journey before adding your accompanying shipment movement documents, your bulk upload of the receipt and/or recovery data will not be saved..
        /// </summary>
        public static string StartText3 {
            get {
                return ResourceManager.GetString("StartText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bulk upload has been successful.
        /// </summary>
        public static string SuccessHeaderText {
            get {
                return ResourceManager.GetString("SuccessHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have uploaded:.
        /// </summary>
        public static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your prenotifications of shipments {0} have now been recorded in the IWS service..
        /// </summary>
        public static string SuccessTextMultipleShipments {
            get {
                return ResourceManager.GetString("SuccessTextMultipleShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your prenotification of shipment {0} has now been recorded in the IWS service..
        /// </summary>
        public static string SuccessTextSingleShipment {
            get {
                return ResourceManager.GetString("SuccessTextSingleShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the data file templates.
        /// </summary>
        public static string TemplateLinkText {
            get {
                return ResourceManager.GetString("TemplateLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data file should not exceed 2GB in size..
        /// </summary>
        public static string UploadReceiptRecoveryList1 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all column headings from a CSV file type..
        /// </summary>
        public static string UploadReceiptRecoveryList2 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only contain shipment records for shipments that have already been prenotified..
        /// </summary>
        public static string UploadReceiptRecoveryList3 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicate receipt or recovery information will be accepted..
        /// </summary>
        public static string UploadReceiptRecoveryList4 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tonnage quantity must not exceed 4 decimal places..
        /// </summary>
        public static string UploadReceiptRecoveryList5 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity unit of measurement must meet the criteria permitted on the notification..
        /// </summary>
        public static string UploadReceiptRecoveryList6 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt / Recovery Bulk Upload.
        /// </summary>
        public static string UploadReceiptRecoveryTabTitle {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the receipt and/or recovery data file in an Excel or .CSV format..
        /// </summary>
        public static string UploadReceiptRecoveryText1 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure all data matches the correct template format to avoid validation errors..
        /// </summary>
        public static string UploadReceiptRecoveryText2 {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk upload of receipt and/or recovery data.
        /// </summary>
        public static string UploadReceiptRecoveryTitle {
            get {
                return ResourceManager.GetString("UploadReceiptRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Errors.
        /// </summary>
        public static string ViewErrors {
            get {
                return ResourceManager.GetString("ViewErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t added any shipment movement documents.
        /// </summary>
        public static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upload shipment movement documents with your receipt and/or recovery data file to finish the process..
        /// </summary>
        public static string WarningText1 {
            get {
                return ResourceManager.GetString("WarningText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave the process before adding your accompanying shipment movement documents, your bulk upload of receipt and/or recovery data will not be saved..
        /// </summary>
        public static string WarningText2 {
            get {
                return ResourceManager.GetString("WarningText2", resourceCulture);
            }
        }
    }
}
