//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.Admin.Views.AdvancedSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.Admin.Views.AdvancedSearch.ResultsResources", typeof(ResultsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to advanced search.
        /// </summary>
        public static string BackToSearch {
            get {
                return ResourceManager.GetString("BackToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basel / OECD code.
        /// </summary>
        public static string BaselCodeTableHeading {
            get {
                return ResourceManager.GetString("BaselCodeTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name (Exporter-notifier).
        /// </summary>
        public static string CompanyNameTableHeading {
            get {
                return ResourceManager.GetString("CompanyNameTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export notifications.
        /// </summary>
        public static string ExportNotificationsHeading {
            get {
                return ResourceManager.GetString("ExportNotificationsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export notification search results.
        /// </summary>
        public static string ExportTableTitle {
            get {
                return ResourceManager.GetString("ExportTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search results.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import notifications.
        /// </summary>
        public static string ImportNotificationsHeading {
            get {
                return ResourceManager.GetString("ImportNotificationsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import notification search results.
        /// </summary>
        public static string ImportTableTitle {
            get {
                return ResourceManager.GetString("ImportTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications matched your search criteria.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification number.
        /// </summary>
        public static string NotificationNumberTableHeading {
            get {
                return ResourceManager.GetString("NotificationNumberTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTableHeading {
            get {
                return ResourceManager.GetString("StatusTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste type.
        /// </summary>
        public static string WasteTypeTableHeading {
            get {
                return ResourceManager.GetString("WasteTypeTableHeading", resourceCulture);
            }
        }
    }
}
