CREATE NONCLUSTERED INDEX [IX_ProducerCache_NotificationNumber] ON [Reports].[ProducerCache]
(
	[CompetentAuthorityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO