//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.CustomWasteCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomWasteCodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomWasteCodeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.CustomWasteCode.CustomWasteCodeRes" +
                            "ources", typeof(CustomWasteCodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomsCode.
        /// </summary>
        public static string CustomsCode {
            get {
                return ResourceManager.GetString("CustomsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a customs code or select not applicable.
        /// </summary>
        public static string CustomsCodeRequired {
            get {
                return ResourceManager.GetString("CustomsCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not applicable is selected please do not enter a code.
        /// </summary>
        public static string DoNotEnterCodeIfNASelected {
            get {
                return ResourceManager.GetString("DoNotEnterCodeIfNASelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National code in country of export.
        /// </summary>
        public static string ExportNationalCode {
            get {
                return ResourceManager.GetString("ExportNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a national code in country of export or select not applicable.
        /// </summary>
        public static string ExportNationalCodeRequired {
            get {
                return ResourceManager.GetString("ExportNationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What other codes apply to the waste?.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any other codes which are relevant to your waste. If no codes are relevant then tick not applicable.
        /// </summary>
        public static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National code in country of import.
        /// </summary>
        public static string ImportNationalCode {
            get {
                return ResourceManager.GetString("ImportNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a national code in country of import or select not applicable.
        /// </summary>
        public static string ImportNationalCodeRequired {
            get {
                return ResourceManager.GetString("ImportNationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other code(s).
        /// </summary>
        public static string OtherCode {
            get {
                return ResourceManager.GetString("OtherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If useful or required by the relevant competent authority add any other code to help identify the waste.
        /// </summary>
        public static string OtherCodeHint {
            get {
                return ResourceManager.GetString("OtherCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter other code(s) or select not applicable.
        /// </summary>
        public static string OtherCodeRequired {
            get {
                return ResourceManager.GetString("OtherCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Identification.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
