//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.Shipment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.Shipment.ShipmentResources", typeof(ShipmentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Day&apos; field.
        /// </summary>
        public static string DayError {
            get {
                return ResourceManager.GetString("DayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number with a maximum of {0} decimal places.
        /// </summary>
        public static string DecimalPlacesValid {
            get {
                return ResourceManager.GetString("DecimalPlacesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first departure date and last departure date must be within a {0} month period.
        /// </summary>
        public static string DepartureDateRange {
            get {
                return ResourceManager.GetString("DepartureDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First departure.
        /// </summary>
        public static string FirstDeparture {
            get {
                return ResourceManager.GetString("FirstDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first departure date must be before the last departure date.
        /// </summary>
        public static string FirstDepartureBeforeLastDate {
            get {
                return ResourceManager.GetString("FirstDepartureBeforeLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, 31 3 2015.
        /// </summary>
        public static string FirstDepartureDateHint {
            get {
                return ResourceManager.GetString("FirstDepartureDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first departure date cannot be in the past.
        /// </summary>
        public static string FirstDeparturePastDate {
            get {
                return ResourceManager.GetString("FirstDeparturePastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid first departure date.
        /// </summary>
        public static string FirstDepartureValid {
            get {
                return ResourceManager.GetString("FirstDepartureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the intended dates of the first and last departure?.
        /// </summary>
        public static string HeaderDates {
            get {
                return ResourceManager.GetString("HeaderDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the total intended number of shipments?.
        /// </summary>
        public static string HeaderNumber {
            get {
                return ResourceManager.GetString("HeaderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the total intended quantity?.
        /// </summary>
        public static string HeaderQty {
            get {
                return ResourceManager.GetString("HeaderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last departure.
        /// </summary>
        public static string LastDeparture {
            get {
                return ResourceManager.GetString("LastDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, 27 11 2015.
        /// </summary>
        public static string LastDepartureDateHint {
            get {
                return ResourceManager.GetString("LastDepartureDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid last departure date.
        /// </summary>
        public static string LastDepartureValid {
            get {
                return ResourceManager.GetString("LastDepartureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Month&apos; field.
        /// </summary>
        public static string MonthError {
            get {
                return ResourceManager.GetString("MonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount can be entered with or without commas as thousand separtors. For example, 3,333 or 3333.
        /// </summary>
        public static string NumberHint {
            get {
                return ResourceManager.GetString("NumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of shipments.
        /// </summary>
        public static string NumberOfShipments {
            get {
                return ResourceManager.GetString("NumberOfShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the total number of intended shipments.
        /// </summary>
        public static string NumberOfShipmentsRequired {
            get {
                return ResourceManager.GetString("NumberOfShipmentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number between 1 and 99999.
        /// </summary>
        public static string NumberOfShipmentsValid {
            get {
                return ResourceManager.GetString("NumberOfShipmentsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the total intended quantity.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Information.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the units..
        /// </summary>
        public static string UnitsRequired {
            get {
                return ResourceManager.GetString("UnitsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Year&apos; field.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
