//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.StateOfImport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateOfImportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateOfImportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.StateOfImport.StateOfImportResourc" +
                            "es", typeof(StateOfImportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competent authority.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the competent authority for the region of import.
        /// </summary>
        public static string CAHint {
            get {
                return ResourceManager.GetString("CAHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the competent authority.
        /// </summary>
        public static string CARequired {
            get {
                return ResourceManager.GetString("CARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change country.
        /// </summary>
        public static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the country or state where the waste ends its journey.
        /// </summary>
        public static string CountryHint {
            get {
                return ResourceManager.GetString("CountryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country list.
        /// </summary>
        public static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the country of import.
        /// </summary>
        public static string CountryOfImportRequired {
            get {
                return ResourceManager.GetString("CountryOfImportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the country or state where the waste ends its journey.
        /// </summary>
        public static string EndJourneyHint {
            get {
                return ResourceManager.GetString("EndJourneyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point.
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the entry point.
        /// </summary>
        public static string EntryPointRequired {
            get {
                return ResourceManager.GetString("EntryPointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit country.
        /// </summary>
        public static string ExitCountry {
            get {
                return ResourceManager.GetString("ExitCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the waste being imported into?.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already selected this country as the country of export. Please select a different country of import..
        /// </summary>
        public static string ImportExportCountryShouldNotSame {
            get {
                return ResourceManager.GetString("ImportExportCountryShouldNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already selected this country as the country of import. Please select a different transit country..
        /// </summary>
        public static string ImportTransitCountryShouldNotSame {
            get {
                return ResourceManager.GetString("ImportTransitCountryShouldNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the specific port or border crossing the waste will enter the country from.
        /// </summary>
        public static string PortHint {
            get {
                return ResourceManager.GetString("PortHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of Import.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
