//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.WhatToDoNext {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralPostResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralPostResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.WhatToDoNext.GeneralPostResources", typeof(GeneralPostResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your company name and notification number on the reverse of your cheque or postal order, and send it with your notification package to the IWS team. Cheques and postal orders should be made payable to The Environment Agency..
        /// </summary>
        public static string EnvironmentAgency {
            get {
                return ResourceManager.GetString("EnvironmentAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your company name and notification number on the reverse of your cheque or postal order, and send it with your notification package to the Hazardous Waste/TFS Section. Cheques and postal orders should be made payable to Department of Agriculture, Environment and Rural Affairs..
        /// </summary>
        public static string Niea {
            get {
                return ResourceManager.GetString("Niea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your company name and notification number on the reverse of your cheque or postal order, and send it with your notification package to the Waste Shipment Unit. Cheques and postal orders should be made payable to Natural Resources Wales..
        /// </summary>
        public static string Nrw {
            get {
                return ResourceManager.GetString("Nrw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your company name and notification number on the reverse of your cheque or postal order, and send it with your notification package to the Producer compliance and Waste Shipments Unit. Cheques and postal orders should be made payable to the Scottish Environmental Protection Agency..
        /// </summary>
        public static string Sepa {
            get {
                return ResourceManager.GetString("Sepa", resourceCulture);
            }
        }
    }
}
