//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.ImportNotification.Views.Shared.EditorTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactViewModelEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactViewModelEditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.ImportNotification.Views.Shared.EditorTemplates.ContactViewModel" +
                            "EditorResources", typeof(ContactViewModelEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be the contact person for the exporter – notifier.
        /// </summary>
        public static string ExporterFullNameHintMsg {
            get {
                return ResourceManager.GetString("ExporterFullNameHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be the contact person for the recovery facility.
        /// </summary>
        public static string FacilityFullNameHintMsg {
            get {
                return ResourceManager.GetString("FacilityFullNameHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be the contact person for the importer – consignee.
        /// </summary>
        public static string ImporterFullNameHintMsg {
            get {
                return ResourceManager.GetString("ImporterFullNameHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be the contact person for the generator – producer.
        /// </summary>
        public static string ProducerFullNameHintMsg {
            get {
                return ResourceManager.GetString("ProducerFullNameHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full telephone number including the international dialling code. For example +00 1234567890.
        /// </summary>
        public static string TelephoneHintMsg {
            get {
                return ResourceManager.GetString("TelephoneHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only up to 3 digits in the telephone prefix field.
        /// </summary>
        public static string TelephonePrefixTitle {
            get {
                return ResourceManager.GetString("TelephonePrefixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their contact person.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
