//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminImportAssessment.ViewModels.KeyDates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyDatesViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyDatesViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminImportAssessment.ViewModels.KeyDates.KeyDatesViewModelResou" +
                            "rces", typeof(KeyDatesViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Started.
        /// </summary>
        public static string CommencementDate {
            get {
                return ResourceManager.GetString("CommencementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;assessment started&apos; date cannot be before “notification received” date. Please enter a different date..
        /// </summary>
        public static string CommencementNotBeforeOthers {
            get {
                return ResourceManager.GetString("CommencementNotBeforeOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;assessment started&apos; date cannot be in the future. Please enter a different date..
        /// </summary>
        public static string CommencementNotInFuture {
            get {
                return ResourceManager.GetString("CommencementNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a &apos;notification received&apos; date before you can continue.
        /// </summary>
        public static string CommencementOthersRequired {
            get {
                return ResourceManager.GetString("CommencementOthersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;notification complete&apos; date cannot be before “notification received” date. Please enter a different date..
        /// </summary>
        public static string CompletedNotBeforeOthers {
            get {
                return ResourceManager.GetString("CompletedNotBeforeOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;notification complete&apos; date cannot be in the future. Please enter a different date..
        /// </summary>
        public static string CompletedNotInFuture {
            get {
                return ResourceManager.GetString("CompletedNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a &apos;notification received&apos; date before you can continue.
        /// </summary>
        public static string CompletedOthersRequired {
            get {
                return ResourceManager.GetString("CompletedOthersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date.
        /// </summary>
        public static string DateRequiredError {
            get {
                return ResourceManager.GetString("DateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision required by.
        /// </summary>
        public static string DecisionDate {
            get {
                return ResourceManager.GetString("DecisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of officer.
        /// </summary>
        public static string NameOfOfficer {
            get {
                return ResourceManager.GetString("NameOfOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the officer cannot be more than 256 characters in length.
        /// </summary>
        public static string NameOfOfficerLengthError {
            get {
                return ResourceManager.GetString("NameOfOfficerLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the officer.
        /// </summary>
        public static string NameOfOfficerRequiredError {
            get {
                return ResourceManager.GetString("NameOfOfficerRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged on.
        /// </summary>
        public static string NotificationAcknowledgedDate {
            get {
                return ResourceManager.GetString("NotificationAcknowledgedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date completed.
        /// </summary>
        public static string NotificationCompletedDate {
            get {
                return ResourceManager.GetString("NotificationCompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification received.
        /// </summary>
        public static string NotificationReceivedDate {
            get {
                return ResourceManager.GetString("NotificationReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment received.
        /// </summary>
        public static string PaymentReceivedDate {
            get {
                return ResourceManager.GetString("PaymentReceivedDate", resourceCulture);
            }
        }
    }
}
