//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminExportAssessment.Views.Annex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnnexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnnexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminExportAssessment.Views.Annex.AnnexResources", typeof(AnnexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string AnnexColumnTitle {
            get {
                return ResourceManager.GetString("AnnexColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document title.
        /// </summary>
        public static string AnnexNameColumnTitle {
            get {
                return ResourceManager.GetString("AnnexNameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download annexes.
        /// </summary>
        public static string DownloadAnnexesTitle {
            get {
                return ResourceManager.GetString("DownloadAnnexesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no annexes required for this notification.
        /// </summary>
        public static string NoAnnexes {
            get {
                return ResourceManager.GetString("NoAnnexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No annex has been uploaded.
        /// </summary>
        public static string NoAnnexUploaded {
            get {
                return ResourceManager.GetString("NoAnnexUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to notification overview.
        /// </summary>
        public static string OverviewLink {
            get {
                return ResourceManager.GetString("OverviewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process of generation.
        /// </summary>
        public static string ProcessOfGeneration {
            get {
                return ResourceManager.GetString("ProcessOfGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology employed.
        /// </summary>
        public static string TechnologyEmployed {
            get {
                return ResourceManager.GetString("TechnologyEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition of waste.
        /// </summary>
        public static string WasteComposition {
            get {
                return ResourceManager.GetString("WasteComposition", resourceCulture);
            }
        }
    }
}
