//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminExportAssessment.ViewModels.FinancialGuaranteeDecision {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinancialGuaranteeDecisionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinancialGuaranteeDecisionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminExportAssessment.ViewModels.FinancialGuaranteeDecision.Fina" +
                            "ncialGuaranteeDecisionResources", typeof(FinancialGuaranteeDecisionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active loads permitted.
        /// </summary>
        public static string ActiveLoadsPermitted {
            get {
                return ResourceManager.GetString("ActiveLoadsPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Active loads permitted must be greater than 0.
        /// </summary>
        public static string ActiveLoadsPermittedGreaterThanZero {
            get {
                return ResourceManager.GetString("ActiveLoadsPermittedGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of active loads permitted.
        /// </summary>
        public static string ActiveLoadsPermittedRequired {
            get {
                return ResourceManager.GetString("ActiveLoadsPermittedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date decision made.
        /// </summary>
        public static string DecisionMadeDate {
            get {
                return ResourceManager.GetString("DecisionMadeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision date cannot be before the completed date of {0}.
        /// </summary>
        public static string DecisionMadeDateNotBeforeCompleteDate {
            get {
                return ResourceManager.GetString("DecisionMadeDateNotBeforeCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision date cannot be in the future.
        /// </summary>
        public static string DecisionMadeDateNotInFuture {
            get {
                return ResourceManager.GetString("DecisionMadeDateNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date the decision was made.
        /// </summary>
        public static string DecisionMadeDateRequired {
            get {
                return ResourceManager.GetString("DecisionMadeDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a decision.
        /// </summary>
        public static string DecisionRequired {
            get {
                return ResourceManager.GetString("DecisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a blanket bond?.
        /// </summary>
        public static string IsBlanketBond {
            get {
                return ResourceManager.GetString("IsBlanketBond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select whether this is a blanket bond or not.
        /// </summary>
        public static string IsBlanketBondRequired {
            get {
                return ResourceManager.GetString("IsBlanketBondRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for refusal.
        /// </summary>
        public static string ReasonForRefusal {
            get {
                return ResourceManager.GetString("ReasonForRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the reason for refusal.
        /// </summary>
        public static string ReasonForRefusalRequired {
            get {
                return ResourceManager.GetString("ReasonForRefusalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the reference number.
        /// </summary>
        public static string ReferenceNumberRequired {
            get {
                return ResourceManager.GetString("ReferenceNumberRequired", resourceCulture);
            }
        }
    }
}
