CREATE TABLE [Reports].[FreedomOfInformationCache] (
	[NotificationNumber] nvarchar(4000)  NULL ,  
	[ImportOrExport] varchar(6)  NOT NULL ,  
	[IsInterim] bit  NULL ,  
	[ReceivedDate] date  NULL ,  
	[CompetentAuthorityId] int  NOT NULL ,  
	[NotifierName] nvarchar(3000)  NOT NULL ,  
	[NotifierAddress] nvarchar(MAX)  NULL ,  
	[NotifierPostalCode] nvarchar(64)  NULL ,  
	[ProducerName] nvarchar(3000)  NOT NULL ,  
	[ProducerAddress] nvarchar(MAX)  NULL ,  
	[ProducerPostalCode] nvarchar(64)  NULL ,  
	[PointOfExport] nvarchar(2048)  NOT NULL ,  
	[PointOfEntry] nvarchar(2048)  NOT NULL ,  
	[ImportCountryName] nvarchar(2048)  NOT NULL ,  
	[ChemicalCompositionTypeId] int  NOT NULL ,  
	[NameOfWaste] nvarchar(264)  NULL ,  
	[EWC] nvarchar(MAX)  NULL ,  
	[YCode] nvarchar(MAX)  NULL ,  
	[HCode] nvarchar(MAX)  NULL ,  
	[OperationCodes] nvarchar(MAX)  NULL ,  
	[ImporterName] nvarchar(3000)  NOT NULL ,  
	[ImporterAddress] nvarchar(MAX)  NULL ,  
	[ImporterPostalCode] nvarchar(64)  NULL ,  
	[FacilityName] nvarchar(3000)  NOT NULL ,  
	[FacilityAddress] nvarchar(MAX)  NULL ,  
	[FacilityPostalCode] nvarchar(64)  NULL ,  
	[IntendedQuantity] decimal(18, 4)  NOT NULL ,  
	[IntendedQuantityUnit] nvarchar(64)  NOT NULL ,  
	[IntendedQuantityUnitId] int  NOT NULL ,  
	[ConsentFrom] date  NULL ,  
	[ConsentTo] date  NULL ,  
	[LocalArea] nvarchar(1024)  NULL ,  
	[MovementNumber] int  NULL ,  
	[MovementReceivedDate] date  NULL ,  
	[MovementCompletedDate] date  NULL ,  
	[MovementQuantityReceviedUnitId] int  NULL ,  
	[MovementQuantityReceived] decimal(18, 4)  NULL );

CREATE TABLE [Reports].[NotificationShipmentDataMissingShipmentsCache] (  
	[NotificationId] uniqueidentifier  NOT NULL ,  
	[NotificationNumber] nvarchar(4000)  NULL ,  
	[CompetentAuthorityId] int  NOT NULL ,  
	[Exporter] nvarchar(3000)  NOT NULL ,  
	[Importer] nvarchar(3000)  NOT NULL ,  
	[Facility] nvarchar(3000)  NOT NULL ,  
	[ShipmentNumber] int  NOT NULL ,  
	[ActualDateOfShipment] date  NULL ,  
	[ConsentFrom] date  NULL ,  
	[ConsentTo] date  NULL ,  
	[PrenotificationDate] date  NULL ,  
	[ReceivedDate] date  NULL ,  
	[CompletedDate] date  NULL ,  
	[QuantityReceived] decimal(18, 4)  NULL ,  
	[QuantityReceivedUnit] nvarchar(64)  NULL ,  
	[QuantityReceivedUnitId] int  NULL ,  
	[ChemicalComposition] nvarchar(MAX)  NULL ,  
	[LocalArea] nvarchar(1024)  NULL ,  
	[TotalQuantity] decimal(18, 4)  NOT NULL ,  
	[TotalQuantityUnits] nvarchar(64)  NOT NULL ,  
	[TotalQuantityUnitsId] int  NOT NULL ,  
	[EntryPort] nvarchar(2048)  NULL ,  
	[DestinationCountry] nvarchar(2048)  NULL ,  
	[ExitPort] nvarchar(2048)  NULL ,  
	[OriginatingCountry] nvarchar(2048)  NULL ,  
	[Status] nvarchar(64)  NULL ,  
	[NotificationReceivedDate] date  NULL ,  
	[EwcCodes] nvarchar(MAX)  NULL );  