namespace EA.Iws.Core.Notification.Audit
{
    public enum NotificationAuditScreenType
    {
        Exporter = 1,
        Producer = 2,
        SiteOfExport = 3,
        Importer = 4,
        RecoveryFacilities = 5,
        DisposalFacilities = 6,
        RecoverySite = 7,
        DisposalSite = 8,
        PreConsentedFacility = 9,
        RecoveryCodes = 10,
        DisposalCodes = 11,
        TechnologyEmployed = 12,
        ReasonForExport = 13,
        IntendedCarrier = 14,
        MeansOfTransport = 15,
        PackagingTypes = 16,
        SpecialHandling = 17,
        ExportRoute = 18,
        ImportRoute = 19,
        Transits = 20,
        CustomsOffice = 21,
        AmountsAndDates = 22,
        ChemicalComposition = 23,
        ChemicalCompositionContinued = 24,
        ProcessOfGeneration = 25,
        PhysicalCharacteristics = 26,
        BaselOecdCodes = 27,
        EwcCodes = 28,
        YCodes = 29,
        HorHpCodes = 30,
        UnClasses = 31,
        UnNumbers = 32,
        OtherCodes = 33,
        WasteRecoveryProvider = 34,
        WasteRecovery = 35,
        WasteRecoveryForDisposal = 36
    }
}
