CREATE TABLE [Lookup].[UnitedKingdomCompetentAuthority]
(
	[Id] INT CONSTRAINT PK_UnitedKingdomCompetentAuthority PRIMARY KEY NOT NULL,
	
	[CompetentAuthorityId] UNIQUEIDENTIFIER CONSTRAINT PK_UnitedKingdomCompetentAuthority_CompetentAuthority FOREIGN KEY REFERENCES [Lookup].[CompetentAuthority],
	[BusinessUnit] NVARCHAR(4000) NOT NULL,
	[UnitedKingdomCountry] NVARCHAR(256) NOT NULL,
	[Building] NVARCHAR(1024) NOT NULL,
	[Address1] NVARCHAR(1024) NOT NULL,
	[Address2] NVARCHAR(1024) NULL,
    [TownOrCity] NVARCHAR(1024) NOT NULL,
	[PostalCode] NVARCHAR(64) NULL,
	[Region] NVARCHAR(1024) NULL,
	[Country] NVARCHAR(1024) NOT NULL,
    [Telephone] NVARCHAR(128) NOT NULL,
	[BacsAccountName] NVARCHAR(4000) NOT NULL,
	[BacsBank] NVARCHAR(2048) NOT NULL,
	[BacsBankAddress] NVARCHAR(MAX) NOT NULL,
	[BacsSortCode] NCHAR(8) NOT NULL,
	[BacsAccountNumber] NVARCHAR(256) NOT NULL,
	[BacsIban] NVARCHAR(256) NOT NULL,
	[BacsSwiftBic] NVARCHAR(256) NOT NULL,
	[BacsEmail] NVARCHAR(256) NULL,
	[BacsFax] NVARCHAR(128) NULL
);
GO

CREATE NONCLUSTERED INDEX IX_UnitedKingdomCompetentAuthority_CompetentAuthority ON [Lookup].[UnitedKingdomCompetentAuthority](CompetentAuthorityId);
GO

INSERT INTO [Lookup].[UnitedKingdomCompetentAuthority]
(
	[Id],
	[UnitedKingdomCountry],
	[CompetentAuthorityId],
	[BusinessUnit],
	[Building],
	[Address1],
	[Address2],
    [TownOrCity],
	[PostalCode],
	[Country],
    [Telephone],
	[BacsAccountName],
	[BacsBank],
	[BacsBankAddress],
	[BacsSortCode],
	[BacsAccountNumber],
	[BacsIban],
	[BacsSwiftBic],
	[BacsEmail],
	[BacsFax]
)
VALUES
(
	1, 
	'England', 
	(SELECT TOP 1 [Id] FROM [Lookup].[CompetentAuthority] WHERE Abbreviation = 'EA'),
	'International Waste Shipments (IWS) Team' ,
	'Richard Fairclough House',
	'Latchford',
	NULL,
	'Warrington',
	'WA4 1HT',
	'United Kingdom',
	'01925 542265',
	'Environment Agency',
	'Citibank',
	'Citigroup Centre, Canada Square, London, E14 5LB',
	'08-33-00',
	'12800543',
	'GB23 CITI0833 0012 8005 43',
	'CITI GB2LXXX',
	'FSC.AR@environment-agency.gov.uk',
	'01733 464892'
),
(
	2, 
	'Scotland', 
	(SELECT TOP 1 [Id] FROM [Lookup].[CompetentAuthority] WHERE Abbreviation = 'SEPA'),
	'Producer Compliance and Waste Shipment Unit',
	'Strathallan House',
	'The Castle Business Park',
	NULL,
	'Stirling',
	'FK9 4TZ',
	'United Kingdom',
	'+44 1786 457700',
	'Scottish Environment Protection Agency',
	'Royal Bank of Scotland',
	'30 Nicholson Street, Edinburgh, EH8 9DL',
	'83-34-00',
	'137187',
	'GB81RBOS83340000137187',
	'RBOSGB2L',
	'Transfrontier@sepa.org.uk',
	'+44 1786 446885'
),
(
	3, 
	'Northern Ireland', 
	(SELECT TOP 1 [Id] FROM [Lookup].[CompetentAuthority] WHERE Abbreviation = 'NIEA'),
	'TFS Section',
	'1st Floor Klondyke Building',
	'Cromac Avenue',
	'Gasworks Business Park, Malone Lower',
	'Belfast',
	'BT7 2JA',
	'United Kingdom',
	'+44 28 90569742',
	'Department of Environment',
	'Northern Bank',
	'8/9 Donegall Square North, Belfast, BT1 5JG',
	'95-01-21',
	'51063634',
	'GB79DABA95012151063634',
	'BICDABAGB2B',
	'TFS@doeni.gov.uk',
	'+442890 569310'
),
(
	4, 
	'Wales', 
	(SELECT TOP 1 [Id] FROM [Lookup].[CompetentAuthority] WHERE Abbreviation = 'NRW'),
	'Waste Shipment Unit',
	'Plas-yr-Afon/Rivers House',
	'St. Mellons Business Park',
	NULL,
	'Cardiff',
	'CF3 0EY',
	'United Kingdom',
	'+44 3000 653073',
	'Natural Resources Wales',
	'Citibank',
	'Citigroup Centre, Canada Square, London, E14 5LB',
	'08-33-00',
	'12800578',
	'GB48CITI08330012800578',
	'CITIGB2LXXX',
	NULL,
	NULL
);