DECLARE @EwcCodes TABLE
(
	Code NVARCHAR(12),
	Description NVARCHAR(3000)
);

INSERT INTO @EwcCodes (Code, Description)
VALUES
(N'01 01 01', N'wastes from mineral metalliferous excavation'),
(N'01 01 02', N'wastes from mineral non-metalliferous excavation'),
(N'01 03 04*', N'acid-generating tailings from processing of sulphide ore'),
(N'01 03 05*', N'other tailings containing hazardous substances'),
(N'01 03 06', N'tailings other than those mentioned in 01 03 04 and 01 03 05'),
(N'01 03 07*', N'other wastes containing hazardous substances from physical and chemical processing of metalliferous minerals'),
(N'01 03 08', N'dusty and powdery wastes other than those mentioned in 01 03 07'),
(N'01 03 09', N'red mud from alumina production other than the wastes mentioned in 01 03 10'),
(N'01 03 10*', N'red mud from alumina production containing hazardous substances other than the wastes mentioned in 01 03 07'),
(N'01 03 99', N'wastes from physical and chemical processing of metalliferous minerals, wastes not otherwise specified'),
(N'01 04 07*', N'wastes containing hazardous substances from physical and chemical processing of non-metalliferous minerals'),
(N'01 04 08', N'waste gravel and crushed rocks other than those mentioned in 01 04 07'),
(N'01 04 09', N'waste sand and clays'),
(N'01 04 10', N'dusty and powdery wastes other than those mentioned in 01 04 07'),
(N'01 04 11', N'wastes from potash and rock salt processing other than those mentioned in 01 04 07'),
(N'01 04 12', N'tailings and other wastes from washing and cleaning of minerals other than those mentioned in 01 04 07 and 01 04 11'),
(N'01 04 13', N'wastes from stone cutting and sawing other than those mentioned in 01 04 07'),
(N'01 04 99', N'wastes from physical and chemical processing of non-metalliferous minerals, wastes not otherwise specified'),
(N'01 05 04', N'freshwater drilling muds and wastes'),
(N'01 05 05*', N'oil-containing drilling muds and wastes'),
(N'01 05 06*', N'drilling muds and other drilling wastes containing hazardous substances'),
(N'01 05 07', N'barite-containing drilling muds and wastes other than those mentioned in 01 05 05 and 01 05 06'),
(N'01 05 08', N'chloride-containing drilling muds and wastes other than those mentioned in 01 05 05 and 01 05 06'),
(N'01 05 99', N'drilling muds and other drilling wastes, wastes not otherwise specified'),
(N'02 01 01', N'sludges from washing and cleaning'),
(N'02 01 02', N'animal-tissue waste'),
(N'02 01 03', N'plant-tissue waste'),
(N'02 01 04', N'waste plastics (except packaging)'),
(N'02 01 06', N'animal faeces, urine and manure (including spoiled straw), effluent, collected separately and treated off-site'),
(N'02 01 07', N'wastes from forestry'),
(N'02 01 08*', N'agrochemical waste containing hazardous substances'),
(N'02 01 09', N'agrochemical waste other than those mentioned in 02 01 08'),
(N'02 01 10', N'waste metal'),
(N'02 01 99', N'wastes from agriculture, horticulture, aquaculture, forestry, hunting and fishing, wastes not otherwise specified'),
(N'02 02 01', N'sludges from washing and cleaning'),
(N'02 02 02', N'animal-tissue waste'),
(N'02 02 03', N'materials unsuitable for consumption or processing'),
(N'02 02 04', N'sludges from on-site effluent treatment'),
(N'02 02 99', N'wastes from the preparation and processing of meat, fish and other foods of animal origin, wastes not otherwise specified'),
(N'02 03 01', N'sludges from washing, cleaning, peeling, centrifuging and separation'),
(N'02 03 02', N'wastes from preserving agents'),
(N'02 03 03', N'wastes from solvent extraction'),
(N'02 03 04', N'materials unsuitable for consumption or processing'),
(N'02 03 05', N'sludges from on-site effluent treatment'),
(N'02 03 99', N'wastes from fruit, vegetables, cereals, edible oils, cocoa, coffee, tea and tobacco preparation and processing; conserve production; yeast and yeast extract production, molasses preparation and fermentation, wastes not otherwise specified'),
(N'02 04 01', N'soil from cleaning and washing beet'),
(N'02 04 02', N'off-specification calcium carbonate'),
(N'02 04 03', N'sludges from on-site effluent treatment'),
(N'02 04 99', N'wastes from sugar processing, wastes not otherwise specified'),
(N'02 05 01', N'materials unsuitable for consumption or processing'),
(N'02 05 02', N'sludges from on-site effluent treatment'),
(N'02 05 99', N'wastes from the dairy products industry, wastes not otherwise specified'),
(N'02 06 01', N'materials unsuitable for consumption or processing'),
(N'02 06 02', N'wastes from preserving agents'),
(N'02 06 03', N'sludges from on-site effluent treatment'),
(N'02 06 99', N'wastes from the baking and confectionery industry, wastes not otherwise specified'),
(N'02 07 01', N'wastes from washing, cleaning and mechanical reduction of raw materials'),
(N'02 07 02', N'wastes from spirits distillation'),
(N'02 07 03', N'wastes from chemical treatment'),
(N'02 07 04', N'materials unsuitable for consumption or processing'),
(N'02 07 05', N'sludges from on-site effluent treatment'),
(N'02 07 99', N'wastes from the production of alcoholic and non-alcoholic beverages (except coffee, tea and cocoa), wastes not otherwise specified'),
(N'03 01 01', N'waste bark and cork'),
(N'03 01 04*', N'sawdust, shavings, cuttings, wood, particle board and veneer containing hazardous substances'),
(N'03 01 05', N'sawdust, shavings, cuttings, wood, particle board and veneer other than those mentioned in 03 01 04'),
(N'03 01 99', N'wastes from wood processing and the production of panels and furniture, wastes not otherwise specified'),
(N'03 02 01*', N'non-halogenated organic wood preservatives'),
(N'03 02 02*', N'organochlorinated wood preservatives'),
(N'03 02 03*', N'organometallic wood preservatives'),
(N'03 02 04*', N'inorganic wood preservatives'),
(N'03 02 05*', N'other wood preservatives containing hazardous substances'),
(N'03 02 99', N'wood preservatives, not otherwise specified'),
(N'03 03 01', N'waste bark and wood'),
(N'03 03 02', N'green liquor sludge (from recovery of cooking liquor)'),
(N'03 03 05', N'de-inking sludges from paper recycling'),
(N'03 03 07', N'mechanically separated rejects from pulping of waste paper and cardboard'),
(N'03 03 08', N'wastes from sorting of paper and cardboard destined for recycling'),
(N'03 03 09', N'lime mud waste'),
(N'03 03 10', N'fibre rejects, fibre-, filler- and coating-sludges from mechanical separation'),
(N'03 03 11', N'sludges from on-site effluent treatment other than those mentioned in 03 03 10'),
(N'03 03 99', N'wastes from wood preservation, wastes not otherwise specified'),
(N'04 01 01', N'fleshings and lime split wastes'),
(N'04 01 02', N'liming waste'),
(N'04 01 03*', N'degreasing wastes containing solvents without a liquid phase'),
(N'04 01 04', N'tanning liquor containing chromium'),
(N'04 01 05', N'tanning liquor free of chromium'),
(N'04 01 06', N'sludges, in particular from on-site effluent treatment containing chromium'),
(N'04 01 07', N'sludges, in particular from on-site effluent treatment free of chromium'),
(N'04 01 08', N'waste tanned leather (blue sheetings, shavings, cuttings, buffing dust) containing chromium'),
(N'04 01 09', N'wastes from dressing and finishing'),
(N'04 01 99', N'wastes from the leather and fur industry, wastes not otherwise specified'),
(N'04 02 09', N'wastes from composite materials (impregnated textile, elastomer, plastomer)'),
(N'04 02 10', N'organic matter from natural products (for example grease, wax)'),
(N'04 02 14*', N'wastes from finishing containing organic solvents'),
(N'04 02 15', N'wastes from finishing other than those mentioned in 04 02 14'),
(N'04 02 16*', N'dyestuffs and pigments containing hazardous substances'),
(N'04 02 17', N'dyestuffs and pigments other than those mentioned in 04 02 16'),
(N'04 02 19*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'04 02 20', N'sludges from on-site effluent treatment other than those mentioned in 04 02 19'),
(N'04 02 21', N'wastes from unprocessed textile fibres'),
(N'04 02 22', N'wastes from processed textile fibres'),
(N'04 02 99', N'wastes from the textile industry, wastes not otherwise specified'),
(N'05 01 02*', N'desalter sludges'),
(N'05 01 03*', N'tank bottom sludges'),
(N'05 01 04*', N'acid alkyl sludges'),
(N'05 01 05*', N'oil spills'),
(N'05 01 06*', N'oily sludges from maintenance operations of the plant or equipment'),
(N'05 01 07*', N'acid tars'),
(N'05 01 08*', N'other tars'),
(N'05 01 09*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'05 01 10', N'sludges from on-site effluent treatment other than those mentioned in 05 01 09'),
(N'05 01 11*', N'wastes from cleaning of fuels with bases'),
(N'05 01 12*', N'oil containing acids'),
(N'05 01 13', N'boiler feedwater sludges'),
(N'05 01 14', N'wastes from cooling columns'),
(N'05 01 15*', N'spent filter clays'),
(N'05 01 16', N'sulphur-containing wastes from petroleum desulphurisation'),
(N'05 01 17', N'Bitumen'),
(N'05 01 99', N'wastes from petroleum refining, wastes not otherwise specified'),
(N'05 06 01*', N'acid tars'),
(N'05 06 03*', N'other tars'),
(N'05 06 04', N'waste from cooling columns'),
(N'05 06 99', N'wastes from the pyrolytic treatment of coal, wastes not otherwise specified'),
(N'05 07 01*', N'wastes containing mercury'),
(N'05 07 02', N'wastes containing sulphur'),
(N'05 07 99', N'wastes from natural gas purification and transportation, wastes not otherwise specified'),
(N'06 01 01*', N'sulphuric acid and sulphurous acid'),
(N'06 01 02*', N'hydrochloric acid'),
(N'06 01 03*', N'hydrofluoric acid'),
(N'06 01 04*', N'phosphoric and phosphorous acid'),
(N'06 01 05*', N'nitric acid and nitrous acid'),
(N'06 01 06*', N'other acids'),
(N'06 01 99', N'wastes from the manufacture, formulation, supply and use (MFSU) of acids, wastes not otherwise specified'),
(N'06 02 01*', N'calcium hydroxide'),
(N'06 02 03*', N'ammonium hydroxide'),
(N'06 02 04*', N'sodium and potassium hydroxide'),
(N'06 02 05*', N'other bases'),
(N'06 02 99', N'wastes from the MFSU of bases, wastes not otherwise specified'),
(N'06 03 11*', N'solid salts and solutions containing cyanides'),
(N'06 03 13*', N'solid salts and solutions containing heavy metals'),
(N'06 03 14', N'solid salts and solutions other than those mentioned in 06 03 11 and 06 03 13'),
(N'06 03 15*', N'metallic oxides containing heavy metals'),
(N'06 03 16', N'metallic oxides other than those mentioned in 06 03 15'),
(N'06 03 99', N'wastes from the MFSU of salts and their solutions and metallic oxides, wastes not otherwise specified'),
(N'06 04 03*', N'wastes containing arsenic'),
(N'06 04 04*', N'wastes containing mercury'),
(N'06 04 05*', N'wastes containing other heavy metals'),
(N'06 04 99', N'metal-containing wastes other than those mentioned in 06 03, wastes not otherwise specified'),
(N'06 05 02*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'06 05 03', N'sludges from on-site effluent treatment other than those mentioned in 06 05 02'),
(N'06 06 02*', N'wastes containing hazardous sulphides'),
(N'06 06 03', N'wastes containing sulphides other than those mentioned in 06 06 02'),
(N'06 06 99', N'wastes from the MFSU of sulphur chemicals, sulphur chemical processes and desulphurisation processes, wastes not otherwise specified'),
(N'06 07 01*', N'wastes containing asbestos from electrolysis'),
(N'06 07 02*', N'activated carbon from chlorine production'),
(N'06 07 03*', N'barium sulphate sludge containing mercury'),
(N'06 07 04*', N'solutions and acids, for example contact acid'),
(N'06 07 99', N'wastes from the MFSU of halogens and halogen chemical processes, wastes not otherwise specified'),
(N'06 08 02*', N'waste containing hazardous chlorosilanes'),
(N'06 08 99', N'wastes from the MFSU of silicon and silicon derivatives, wastes not otherwise specified'),
(N'06 09 02', N'phosphorous slag'),
(N'06 09 03*', N'calcium-based reaction wastes containing or contaminated with hazardous substances'),
(N'06 09 04', N'calcium-based reaction wastes other than those mentioned in 06 09 03'),
(N'06 09 99', N'wastes from the MSFU of phosphorous chemicals and phosphorous chemical processes, wastes not otherwise specified'),
(N'06 10 02*', N'wastes containing hazardous substances'),
(N'06 10 99', N'wastes from the MFSU of nitrogen chemicals, nitrogen chemical processes and fertiliser manufacture, wastes not otherwise specified'),
(N'06 11 01', N'calcium-based reaction wastes from titanium dioxide production'),
(N'06 11 99', N'wastes from the manufacture of inorganic pigments and opacificiers, wastes not otherwise specified'),
(N'06 13 01*', N'inorganic plant protection products, wood-preserving agents and other biocides.'),
(N'06 13 02*', N'spent activated carbon (except 06 07 02)'),
(N'06 13 03', N'carbon black'),
(N'06 13 04*', N'wastes from asbestos processing'),
(N'06 13 05*', N'Soot'),
(N'06 13 99', N'wastes from inorganic chemical processes not otherwise specified, wastes not otherwise specified'),
(N'07 01 01*', N'aqueous washing liquids and mother liquors'),
(N'07 01 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 01 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 01 07*', N'halogenated still bottoms and reaction residues'),
(N'07 01 08*', N'other still bottoms and reaction residues'),
(N'07 01 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 01 10*', N'other filter cakes and spent absorbents'),
(N'07 01 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 01 12', N'sludges from on-site effluent treatment other than those mentioned in 07 01 11'),
(N'07 01 99', N'wastes from the manufacture, formulation, supply and use (MFSU) of basic organic chemicals, wastes not otherwise specified'),
(N'07 02 01*', N'aqueous washing liquids and mother liquors'),
(N'07 02 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 02 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 02 07*', N'halogenated still bottoms and reaction residues'),
(N'07 02 08*', N'other still bottoms and reaction residues'),
(N'07 02 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 02 10*', N'other filter cakes and spent absorbents'),
(N'07 02 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 02 12', N'sludges from on-site effluent treatment other than those mentioned in 07 02 11'),
(N'07 02 13', N'waste plastic'),
(N'07 02 14*', N'wastes from additives containing hazardous substances'),
(N'07 02 15', N'wastes from additives other than those mentioned in 07 02 14'),
(N'07 02 16*', N'waste containing hazardous silicones'),
(N'07 02 17', N'waste containing silicones other than those mentioned in 07 02 16'),
(N'07 02 99', N'wastes from the MFSU of plastics, synthetic rubber and man-made fibres, wastes not otherwise specified'),
(N'07 03 01*', N'aqueous washing liquids and mother liquors'),
(N'07 03 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 03 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 03 07*', N'halogenated still bottoms and reaction residues'),
(N'07 03 08*', N'other still bottoms and reaction residues'),
(N'07 03 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 03 10*', N'other filter cakes and spent absorbents'),
(N'07 03 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 03 12', N'sludges from on-site effluent treatment other than those mentioned in 07 03 11'),
(N'07 03 99', N'wastes from the MFSU of organic dyes and pigments (except 06 11), wastes not otherwise specified'),
(N'07 04 01*', N'aqueous washing liquids and mother liquors'),
(N'07 04 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 04 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 04 07*', N'halogenated still bottoms and reaction residues'),
(N'07 04 08*', N'other still bottoms and reaction residues'),
(N'07 04 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 04 10*', N'other filter cakes and spent absorbents'),
(N'07 04 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 04 12', N'sludges from on-site effluent treatment other than those mentioned in 07 04 11'),
(N'07 04 13*', N'solid wastes containing hazardous substances'),
(N'07 04 99', N'wastes from the MFSU of organic plant protection products (except 02 01 08 and 02 01 09), wood preserving agents (except 03 02) and other biocides, wastes not otherwise specified'),
(N'07 05 01*', N'aqueous washing liquids and mother liquors'),
(N'07 05 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 05 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 05 07*', N'halogenated still bottoms and reaction residues'),
(N'07 05 08*', N'other still bottoms and reaction residues'),
(N'07 05 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 05 10*', N'other filter cakes and spent absorbents'),
(N'07 05 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 05 12', N'sludges from on-site effluent treatment other than those mentioned in 07 05 11'),
(N'07 05 13*', N'solid wastes containing hazardous substances'),
(N'07 05 14', N'solid wastes other than those mentioned in 07 05 13'),
(N'07 05 99', N'wastes from the MFSU of pharmaceuticals, wastes not otherwise specified'),
(N'07 06 01*', N'aqueous washing liquids and mother liquors'),
(N'07 06 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 06 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 06 07*', N'halogenated still bottoms and reaction residues'),
(N'07 06 08*', N'other still bottoms and reaction residues'),
(N'07 06 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 06 10*', N'other filter cakes and spent absorbents'),
(N'07 06 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 06 12', N'sludges from on-site effluent treatment other than those mentioned in 07 06 11'),
(N'07 06 99', N'wastes from the MFSU of fats, grease, soaps, detergents, disinfectants and cosmetics, wastes not otherwise specified'),
(N'07 07 01*', N'aqueous washing liquids and mother liquors'),
(N'07 07 03*', N'organic halogenated solvents, washing liquids and mother liquors'),
(N'07 07 04*', N'other organic solvents, washing liquids and mother liquors'),
(N'07 07 07*', N'halogenated still bottoms and reaction residues'),
(N'07 07 08*', N'other still bottoms and reaction residues'),
(N'07 07 09*', N'halogenated filter cakes and spent absorbents'),
(N'07 07 10*', N'other filter cakes and spent absorbents'),
(N'07 07 11*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'07 07 12', N'sludges from on-site effluent treatment other than those mentioned in 07 07 11'),
(N'07 07 99', N'wastes from the MFSU of fine chemicals and chemical products not otherwise specified, wastes not otherwise specified'),
(N'08 01 11*', N'waste paint and varnish containing organic solvents or other hazardous substances'),
(N'08 01 12', N'waste paint and varnish other than those mentioned in 08 01 11'),
(N'08 01 13*', N'sludges from paint or varnish containing organic solvents or other hazardous substances'),
(N'08 01 14', N'sludges from paint or varnish other than those mentioned in 08 01 13'),
(N'08 01 15*', N'aqueous sludges containing paint or varnish containing organic solvents or other hazardous substances'),
(N'08 01 16', N'aqueous sludges containing paint or varnish other than those mentioned in 08 01 15'),
(N'08 01 17*', N'wastes from paint or varnish removal containing organic solvents or other hazardous substances'),
(N'08 01 18', N'wastes from paint or varnish removal other than those mentioned in 08 01 17'),
(N'08 01 19*', N'aqueous suspensions containing paint or varnish containing organic solvents or other hazardous substances'),
(N'08 01 20', N'aqueous suspensions containing paint or varnish other than those mentioned in 08 01 19'),
(N'08 01 21*', N'waste paint or varnish remover'),
(N'08 01 99', N'wastes from MFSU and removal of paint and varnish, wastes not otherwise specified'),
(N'08 02 01', N'waste coating powders'),
(N'08 02 02', N'aqueous sludges containing ceramic materials'),
(N'08 02 03', N'aqueous suspensions containing ceramic materials'),
(N'08 02 99', N'wastes from MFSU of other coatings (including ceramic materials), wastes not otherwise specified'),
(N'08 03 07', N'aqueous sludges containing ink'),
(N'08 03 08', N'aqueous liquid waste containing ink'),
(N'08 03 12*', N'waste ink containing hazardous substances'),
(N'08 03 13', N'waste ink other than those mentioned in 08 03 12'),
(N'08 03 14*', N'ink sludges containing hazardous substances'),
(N'08 03 15', N'ink sludges other than those mentioned in 08 03 14'),
(N'08 03 16*', N'waste etching solutions'),
(N'08 03 17*', N'waste printing toner containing hazardous substances'),
(N'08 03 18', N'waste printing toner other than those mentioned in 08 03 17'),
(N'08 03 19*', N'disperse oil'),
(N'08 03 99', N'wastes from MFSU of printing inks, wastes not otherwise specified'),
(N'08 04 09*', N'waste adhesives and sealants containing organic solvents or other hazardous substances'),
(N'08 04 10', N'waste adhesives and sealants other than those mentioned in 08 04 09'),
(N'08 04 11*', N'adhesive and sealant sludges containing organic solvents or other hazardous substances'),
(N'08 04 12', N'adhesive and sealant sludges other than those mentioned in 08 04 11'),
(N'08 04 13*', N'aqueous sludges containing adhesives or sealants containing organic solvents or other hazardous substances'),
(N'08 04 14', N'aqueous sludges containing adhesives or sealants other than those mentioned in 08 04 13'),
(N'08 04 15*', N'aqueous liquid waste containing adhesives or sealants containing organic solvents or other hazardous substances'),
(N'08 04 16', N'aqueous liquid waste containing adhesives or sealants other than those mentioned in 08 04 15'),
(N'08 04 17*', N'rosin oil'),
(N'08 04 99', N'wastes from MFSU of adhesives and sealants (including waterproofing products), wastes not otherwise specified'),
(N'08 05 01*', N'waste isocyanates'),
(N'09 01 01*', N'water-based developer and activator solutions'),
(N'09 01 02*', N'water-based offset plate developer solutions'),
(N'09 01 03*', N'solvent-based developer solutions'),
(N'09 01 04*', N'fixer solutions'),
(N'09 01 05*', N'bleach solutions and bleach fixer solutions'),
(N'09 01 06*', N'wastes containing silver from on-site treatment of photographic wastes'),
(N'09 01 07', N'photographic film and paper containing silver or silver compounds'),
(N'09 01 08', N'photographic film and paper free of silver or silver compounds'),
(N'09 01 10', N'single-use cameras without batteries'),
(N'09 01 11*', N'single-use cameras containing batteries included in 16 06 01, 16 06 02 or 16 06 03'),
(N'09 01 12', N'single-use cameras containing batteries other than those mentioned in 09 01 11'),
(N'09 01 13*', N'aqueous liquid waste from on-site reclamation of silver other than those mentioned in 09 01 06'),
(N'09 01 99', N'wastes from the photographic industry, wastes not otherwise specified'),
(N'10 01 01', N'bottom ash, slag and boiler dust (excluding boiler dust mentioned in 10 01 04)'),
(N'10 01 02', N'coal fly ash'),
(N'10 01 03', N'fly ash from peat and untreated wood'),
(N'10 01 04*', N'oil fly ash and boiler dust'),
(N'10 01 05', N'calcium-based reaction wastes from flue-gas desulphurisation in solid form'),
(N'10 01 07', N'calcium-based reaction wastes from flue-gas desulphurisation in sludge form'),
(N'10 01 09*', N'sulphuric acid'),
(N'10 01 13*', N'fly ash from emulsified hydrocarbons used as fuel'),
(N'10 01 14*', N'bottom ash, slag and boiler dust from co-incineration containing hazardous substances'),
(N'10 01 15', N'bottom ash, slag and boiler dust from co-incineration other than those mentioned in 10 01 14'),
(N'10 01 16*', N'fly ash from co-incineration containing hazardous substances'),
(N'10 01 17', N'fly ash from co-incineration other than those mentioned in 10 01 16'),
(N'10 01 18*', N'wastes from gas cleaning containing hazardous substances'),
(N'10 01 19', N'wastes from gas cleaning other than those mentioned in 10 01 05, 10 01 07 and 10 01 18'),
(N'10 01 20*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'10 01 21', N'sludges from on-site effluent treatment other than those mentioned in 10 01 20'),
(N'10 01 22*', N'aqueous sludges from boiler cleansing containing hazardous substances'),
(N'10 01 23', N'aqueous sludges from boiler cleansing other than those mentioned in 10 01 22'),
(N'10 01 24', N'sands from fluidised beds'),
(N'10 01 25', N'wastes from fuel storage and preparation of coal-fired power plants'),
(N'10 01 26', N'wastes from cooling-water treatment'),
(N'10 01 99', N'wastes from power stations and other combustion plants (except 19), wastes not otherwise specified'),
(N'10 02 01', N'wastes from the processing of slag'),
(N'10 02 02', N'unprocessed slag'),
(N'10 02 07*', N'solid wastes from gas treatment containing hazardous substances'),
(N'10 02 08', N'solid wastes from gas treatment other than those mentioned in 10 02 07'),
(N'10 02 10', N'mill scales'),
(N'10 02 11*', N'wastes from cooling-water treatment containing oil'),
(N'10 02 12', N'wastes from cooling-water treatment other than those mentioned in 10 02 11'),
(N'10 02 13*', N'sludges and filter cakes from gas treatment containing hazardous substances'),
(N'10 02 14', N'sludges and filter cakes from gas treatment other than those mentioned in 10 02 13'),
(N'10 02 15', N'other sludges and filter cakes'),
(N'10 02 99', N'wastes from the iron and steel industry, wastes not otherwise specified'),
(N'10 03 02', N'anode scraps'),
(N'10 03 04*', N'primary production slags'),
(N'10 03 05', N'waste alumina'),
(N'10 03 08*', N'salt slags from secondary production'),
(N'10 03 09*', N'black drosses from secondary production'),
(N'10 03 15*', N'skimmings that are flammable or emit, upon contact with water, flammable gases in hazardous quantities'),
(N'10 03 16', N'skimmings other than those mentioned in 10 03 15'),
(N'10 03 17*', N'tar-containing wastes from anode manufacture'),
(N'10 03 18', N'carbon-containing wastes from anode manufacture other than those mentioned in 10 03 17'),
(N'10 03 19*', N'flue-gas dust containing hazardous substances'),
(N'10 03 20', N'flue-gas dust other than those mentioned in 10 03 19'),
(N'10 03 21*', N'other particulates and dust (including ball-mill dust) containing hazardous substances'),
(N'10 03 22', N'other particulates and dust (including ball-mill dust) other than those mentioned in 10 03 21'),
(N'10 03 23*', N'solid wastes from gas treatment containing hazardous substances'),
(N'10 03 24', N'solid wastes from gas treatment other than those mentioned in 10 03 23'),
(N'10 03 25*', N'sludges and filter cakes from gas treatment containing hazardous substances'),
(N'10 03 26', N'sludges and filter cakes from gas treatment other than those mentioned in 10 03 25'),
(N'10 03 27*', N'wastes from cooling-water treatment containing oil'),
(N'10 03 28', N'wastes from cooling-water treatment other than those mentioned in 10 03 27'),
(N'10 03 29*', N'wastes from treatment of salt slags and black drosses containing hazardous substances'),
(N'10 03 30', N'wastes from treatment of salt slags and black drosses other than those mentioned in 10 03 29'),
(N'10 03 99', N'wastes from aluminium thermal metallurgy, wastes not otherwise specified'),
(N'10 04 01*', N'slags from primary and secondary production'),
(N'10 04 02*', N'dross and skimmings from primary and secondary production'),
(N'10 04 03*', N'calcium arsenate'),
(N'10 04 04*', N'flue-gas dust'),
(N'10 04 05*', N'other particulates and dust'),
(N'10 04 06*', N'solid wastes from gas treatment'),
(N'10 04 07*', N'sludges and filter cakes from gas treatment'),
(N'10 04 09*', N'wastes from cooling-water treatment containing oil'),
(N'10 04 10', N'wastes from cooling-water treatment other than those mentioned in 10 04 09'),
(N'10 04 99', N'wastes from lead thermal metallurgy, wastes not otherwise specified'),
(N'10 05 01', N'slags from primary and secondary production'),
(N'10 05 03*', N'flue-gas dust'),
(N'10 05 04', N'other particulates and dust'),
(N'10 05 05*', N'solid waste from gas treatment'),
(N'10 05 06*', N'sludges and filter cakes from gas treatment'),
(N'10 05 08*', N'wastes from cooling-water treatment containing oil'),
(N'10 05 09', N'wastes from cooling-water treatment other than those mentioned in 10 05 08'),
(N'10 05 10*', N'dross and skimmings that are flammable or emit, upon contact with water, flammable gases in hazardous quantities'),
(N'10 05 11', N'dross and skimmings other than those mentioned in 10 05 10'),
(N'10 05 99', N'wastes from zinc thermal metallurgy, wastes not otherwise specified'),
(N'10 06 01', N'slags from primary and secondary production'),
(N'10 06 02', N'dross and skimmings from primary and secondary production'),
(N'10 06 03*', N'flue-gas dust'),
(N'10 06 04', N'other particulates and dust'),
(N'10 06 06*', N'solid wastes from gas treatment'),
(N'10 06 07*', N'sludges and filter cakes from gas treatment'),
(N'10 06 09*', N'wastes from cooling-water treatment containing oil'),
(N'10 06 10', N'wastes from cooling-water treatment other than those mentioned in 10 06 09'),
(N'10 06 99', N'wastes from copper thermal metallurgy, wastes not otherwise specified'),
(N'10 07 01', N'slags from primary and secondary production'),
(N'10 07 02', N'dross and skimmings from primary and secondary production'),
(N'10 07 03', N'solid wastes from gas treatment'),
(N'10 07 04', N'other particulates and dust'),
(N'10 07 05', N'sludges and filter cakes from gas treatment'),
(N'10 07 07*', N'wastes from cooling-water treatment containing oil'),
(N'10 07 08', N'wastes from cooling-water treatment other than those mentioned in 10 07 07'),
(N'10 07 99', N'wastes from silver, gold and platinum thermal metallurgy, wastes not otherwise specified'),
(N'10 08 04', N'particulates and dust'),
(N'10 08 08*', N'salt slag from primary and secondary production'),
(N'10 08 09', N'other slags'),
(N'10 08 10*', N'dross and skimmings that are flammable or emit, upon contact with water, flammable gases in hazardous quantities'),
(N'10 08 11', N'dross and skimmings other than those mentioned in 10 08 10'),
(N'10 08 12*', N'tar-containing wastes from anode manufacture'),
(N'10 08 13', N'carbon-containing wastes from anode manufacture other than those mentioned in 10 08 12'),
(N'10 08 14', N'anode scrap'),
(N'10 08 15*', N'flue-gas dust containing hazardous substances'),
(N'10 08 16', N'flue-gas dust other than those mentioned in 10 08 15'),
(N'10 08 17*', N'sludges and filter cakes from flue-gas treatment containing hazardous substances'),
(N'10 08 18', N'sludges and filter cakes from flue-gas treatment other than those mentioned in 10 08 17'),
(N'10 08 19*', N'wastes from cooling-water treatment containing oil'),
(N'10 08 20', N'wastes from cooling-water treatment other than those mentioned in 10 08 19'),
(N'10 08 99', N'wastes from other non-ferrous thermal metallurgy, wastes not otherwise specified'),
(N'10 09 03', N'furnace slag'),
(N'10 09 05*', N'casting cores and moulds which have not undergone pouring containing hazardous substances'),
(N'10 09 06', N'casting cores and moulds which have not undergone pouring other than those mentioned in 10 09 05'),
(N'10 09 07*', N'casting cores and moulds which have undergone pouring containing hazardous substances'),
(N'10 09 08', N'casting cores and moulds which have undergone pouring other than those mentioned in 10 09 07'),
(N'10 09 09*', N'flue-gas dust containing hazardous substances'),
(N'10 09 10', N'flue-gas dust other than those mentioned in 10 09 09'),
(N'10 09 11*', N'other particulates containing hazardous substances'),
(N'10 09 12', N'other particulates other than those mentioned in 10 09 11'),
(N'10 09 13*', N'waste binders containing hazardous substances'),
(N'10 09 14', N'waste binders other than those mentioned in 10 09 13'),
(N'10 09 15*', N'waste crack-indicating agent containing hazardous substances'),
(N'10 09 16', N'waste crack-indicating agent other than those mentioned in 10 09 15'),
(N'10 09 99', N'wastes from casting of ferrous pieces, wastes not otherwise specified'),
(N'10 10 03', N'furnace slag'),
(N'10 10 05*', N'casting cores and moulds which have not undergone pouring, containing hazardous substances'),
(N'10 10 06', N'casting cores and moulds which have not undergone pouring, other than those mentioned in 10 10 05'),
(N'10 10 07*', N'casting cores and moulds which have undergone pouring, containing hazardous substances'),
(N'10 10 08', N'casting cores and moulds which have undergone pouring, other than those mentioned in 10 10 07'),
(N'10 10 09*', N'flue-gas dust containing hazardous substances'),
(N'10 10 10', N'flue-gas dust other than those mentioned in 10 10 09'),
(N'10 10 11*', N'other particulates containing hazardous substances'),
(N'10 10 12', N'other particulates other than those mentioned in 10 10 11'),
(N'10 10 13*', N'waste binders containing hazardous substances'),
(N'10 10 14', N'waste binders other than those mentioned in 10 10 13'),
(N'10 10 15*', N'waste crack-indicating agent containing hazardous substances'),
(N'10 10 16', N'waste crack-indicating agent other than those mentioned in 10 10 15'),
(N'10 10 99', N'wastes from casting of non-ferrous pieces, wastes not otherwise specified'),
(N'10 11 03', N'waste glass-based fibrous materials'),
(N'10 11 05', N'particulates and dust'),
(N'10 11 09*', N'waste preparation mixture before thermal processing, containing hazardous substances'),
(N'10 11 10', N'waste preparation mixture before thermal processing, other than those mentioned in 10 11 09'),
(N'10 11 11*', N'waste glass in small particles and glass powder containing heavy metals (for example from cathode ray tubes)'),
(N'10 11 12', N'waste glass other than those mentioned in 10 11 11'),
(N'10 11 13*', N'glass-polishing and -grinding sludge containing hazardous substances'),
(N'10 11 14', N'glass-polishing and -grinding sludge other than those mentioned in 10 11 13'),
(N'10 11 15*', N'solid wastes from flue-gas treatment containing hazardous substances'),
(N'10 11 16', N'solid wastes from flue-gas treatment other than those mentioned in 10 11 15'),
(N'10 11 17*', N'sludges and filter cakes from flue-gas treatment containing hazardous substances'),
(N'10 11 18', N'sludges and filter cakes from flue-gas treatment other than those mentioned in 10 11 17'),
(N'10 11 19*', N'solid wastes from on-site effluent treatment containing hazardous substances'),
(N'10 11 20', N'solid wastes from on-site effluent treatment other than those mentioned in 10 11 19'),
(N'10 11 99', N'wastes from manufacture of glass and glass products, wastes not otherwise specified'),
(N'10 12 01', N'waste preparation mixture before thermal processing'),
(N'10 12 03', N'particulates and dust'),
(N'10 12 05', N'sludges and filter cakes from gas treatment'),
(N'10 12 06', N'discarded moulds'),
(N'10 12 08', N'waste ceramics, bricks, tiles and construction products (after thermal processing)'),
(N'10 12 09*', N'solid wastes from gas treatment containing hazardous substances'),
(N'10 12 10', N'solid wastes from gas treatment other than those mentioned in 10 12 09'),
(N'10 12 11*', N'wastes from glazing containing heavy metals'),
(N'10 12 12', N'wastes from glazing other than those mentioned in 10 12 11'),
(N'10 12 13', N'sludge from on-site effluent treatment'),
(N'10 12 99', N'wastes from manufacture of ceramic goods, bricks, tiles and construction products, wastes not otherwise specified'),
(N'10 13 01', N'waste preparation mixture before thermal processing'),
(N'10 13 04', N'wastes from calcination and hydration of lime'),
(N'10 13 06', N'particulates and dust (except 10 13 12 and 10 13 13)'),
(N'10 13 07', N'sludges and filter cakes from gas treatment'),
(N'10 13 09*', N'wastes from asbestos-cement manufacture containing asbestos'),
(N'10 13 10', N'wastes from asbestos-cement manufacture other than those mentioned in 10 13 09'),
(N'10 13 11', N'wastes from cement-based composite materials other than those mentioned in 10 13 09 and 10 13 10'),
(N'10 13 12*', N'solid wastes from gas treatment containing hazardous substances'),
(N'10 13 13', N'solid wastes from gas treatment other than those mentioned in 10 13 12'),
(N'10 13 14', N'waste concrete and concrete sludge'),
(N'10 13 99', N'wastes from manufacture of cement, lime and plaster and articles and products made from them, wastes not otherwise specified'),
(N'10 14 01*', N'waste from gas cleaning containing mercury'),
(N'11 01 05*', N'pickling acids'),
(N'11 01 06*', N'acids not otherwise specified'),
(N'11 01 07*', N'pickling bases'),
(N'11 01 08*', N'phosphatising sludges'),
(N'11 01 09*', N'sludges and filter cakes containing hazardous substances'),
(N'11 01 10', N'sludges and filter cakes other than those mentioned in 11 01 09'),
(N'11 01 11*', N'aqueous rinsing liquids containing hazardous substances'),
(N'11 01 12', N'aqueous rinsing liquids other than those mentioned in 11 01 11'),
(N'11 01 13*', N'degreasing wastes containing hazardous substances'),
(N'11 01 14', N'degreasing wastes other than those mentioned in 11 01 13'),
(N'11 01 15*', N'eluate and sludges from membrane systems or ion exchange systems containing hazardous substances'),
(N'11 01 16*', N'saturated or spent ion exchange resins'),
(N'11 01 98*', N'other wastes containing hazardous substances'),
(N'11 01 99', N'wastes from chemical surface treatment and coating of metals and other materials (for example galvanic processes, zinc coating processes, pickling processes, etching, phosphating, alkaline degreasing, anodising), wastes not otherwise specified'),
(N'11 02 02*', N'sludges from zinc hydrometallurgy (including jarosite, goethite)'),
(N'11 02 03', N'wastes from the production of anodes for aqueous electrolytical processes'),
(N'11 02 05*', N'wastes from copper hydrometallurgical processes containing hazardous substances'),
(N'11 02 06', N'wastes from copper hydrometallurgical processes other than those mentioned in 11 02 05'),
(N'11 02 07*', N'other wastes containing hazardous substances'),
(N'11 02 99', N'wastes from non-ferrous hydrometallurgical processes, wastes not otherwise specified'),
(N'11 03 01*', N'wastes containing cyanide'),
(N'11 03 02*', N'sludges and solids from tempering processes, other wastes'),
(N'11 05 01', N'hard zinc'),
(N'11 05 02', N'zinc ash'),
(N'11 05 03*', N'solid wastes from gas treatment'),
(N'11 05 04*', N'spent flux'),
(N'11 05 99', N'wastes from hot galvanising processes, wastes not otherwise specified'),
(N'12 01 01', N'ferrous metal filings and turnings'),
(N'12 01 02', N'ferrous metal dust and particles'),
(N'12 01 03', N'non-ferrous metal filings and turnings'),
(N'12 01 04', N'non-ferrous metal dust and particles'),
(N'12 01 05', N'plastics shavings and turnings'),
(N'12 01 06*', N'mineral-based machining oils containing halogens (except emulsions and solutions)'),
(N'12 01 07*', N'mineral-based machining oils free of halogens (except emulsions and solutions)'),
(N'12 01 08*', N'machining emulsions and solutions containing halogens'),
(N'12 01 09*', N'machining emulsions and solutions free of halogens'),
(N'12 01 10*', N'synthetic machining oils'),
(N'12 01 12*', N'spent waxes and fats'),
(N'12 01 13', N'welding wastes'),
(N'12 01 14*', N'machining sludges containing hazardous substances'),
(N'12 01 15', N'machining sludges other than those mentioned in 12 01 14'),
(N'12 01 16*', N'waste blasting material containing hazardous substances'),
(N'12 01 17', N'waste blasting material other than those mentioned in 12 01 16'),
(N'12 01 18*', N'metal sludge (grinding, honing and lapping sludge) containing oil'),
(N'12 01 19*', N'readily biodegradable machining oil'),
(N'12 01 20*', N'spent grinding bodies and grinding materials containing hazardous substances'),
(N'12 01 21', N'spent grinding bodies and grinding materials other than those mentioned in 12 01 20'),
(N'12 01 99', N'wastes from shaping and physical and mechanical surface treatment of metals and plastics, wastes not otherwise specified'),
(N'12 03 01*', N'aqueous washing liquids'),
(N'12 03 02*', N'steam degreasing wastes'),
(N'13 01 01*', N'hydraulic oils, containing PCBs'),
(N'13 01 04*', N'chlorinated emulsions'),
(N'13 01 05*', N'non-chlorinated emulsions'),
(N'13 01 09*', N'mineral-based chlorinated hydraulic oils'),
(N'13 01 10*', N'mineral based non-chlorinated hydraulic oils'),
(N'13 01 11*', N'synthetic hydraulic oils'),
(N'13 01 12*', N'readily biodegradable hydraulic oils'),
(N'13 01 13*', N'other hydraulic oils'),
(N'13 02 04*', N'mineral-based chlorinated engine, gear and lubricating oils'),
(N'13 02 05*', N'mineral-based non-chlorinated engine, gear and lubricating oils'),
(N'13 02 06*', N'synthetic engine, gear and lubricating oils'),
(N'13 02 07*', N'readily biodegradable engine, gear and lubricating oils'),
(N'13 02 08*', N'other engine, gear and lubricating oils'),
(N'13 03 01*', N'insulating or heat transmission oils containing PCBs'),
(N'13 03 06*', N'mineral-based chlorinated insulating and heat transmission oils other than those mentioned in 13 03 01'),
(N'13 03 07*', N'mineral-based non-chlorinated insulating and heat transmission oils'),
(N'13 03 08*', N'synthetic insulating and heat transmission oils'),
(N'13 03 09*', N'readily biodegradable insulating and heat transmission oils'),
(N'13 03 10*', N'other insulating and heat transmission oils'),
(N'13 04 01*', N'bilge oils from inland navigation'),
(N'13 04 02*', N'bilge oils from jetty sewers'),
(N'13 04 03*', N'bilge oils from other navigation'),
(N'13 05 01*', N'solids from grit chambers and oil/water separators'),
(N'13 05 02*', N'sludges from oil/water separators'),
(N'13 05 03*', N'interceptor sludges'),
(N'13 05 06*', N'oil from oil/water separators'),
(N'13 05 07*', N'oily water from oil/water separators'),
(N'13 05 08*', N'mixtures of wastes from grit chambers and oil/water separators'),
(N'13 07 01*', N'fuel oil and diesel'),
(N'13 07 02*', N'Petrol'),
(N'13 07 03*', N'other fuels (including mixtures)'),
(N'13 08 01*', N'desalter sludges or emulsions'),
(N'13 08 02*', N'other emulsions'),
(N'13 08 99*', N'wastes from water and steam degreasing processes (except 11), wastes not otherwise specified'),
(N'14 06 01*', N'chlorofluorocarbons, HCFC, HFC'),
(N'14 06 02*', N'other halogenated solvents and solvent mixtures'),
(N'14 06 03*', N'other solvents and solvent mixtures'),
(N'14 06 04*', N'sludges or solid wastes containing halogenated solvents'),
(N'14 06 05*', N'sludges or solid wastes containing other solvents'),
(N'15 01 01', N'paper and cardboard packaging'),
(N'15 01 02', N'plastic packaging'),
(N'15 01 03', N'wooden packaging'),
(N'15 01 04', N'metallic packaging'),
(N'15 01 05', N'composite packaging'),
(N'15 01 06', N'mixed packaging'),
(N'15 01 07', N'glass packaging'),
(N'15 01 09', N'textile packaging'),
(N'15 01 10*', N'packaging containing residues of or contaminated by hazardous substances'),
(N'15 01 11*', N'metallic packaging containing a hazardous solid porous matrix (for example asbestos), including empty pressure containers'),
(N'15 02 02*', N'absorbents, filter materials (including oil filters not otherwise specified), wiping cloths, protective clothing contaminated by hazardous substances'),
(N'15 02 03', N'absorbents, filter materials, wiping cloths and protective clothing other than those mentioned in 15 02 02'),
(N'16 01 03', N'end-of-life tyres'),
(N'16 01 04*', N'end-of-life vehicles'),
(N'16 01 06', N'end-of-life vehicles, containing neither liquids nor other hazardous components'),
(N'16 01 07*', N'oil filters'),
(N'16 01 08*', N'components containing mercury'),
(N'16 01 09*', N'components containing PCBs'),
(N'16 01 10*', N'explosive components (for example air bags)'),
(N'16 01 11*', N'brake pads containing asbestos'),
(N'16 01 12', N'brake pads other than those mentioned in 16 01 11'),
(N'16 01 13*', N'brake fluids'),
(N'16 01 14*', N'antifreeze fluids containing hazardous substances'),
(N'16 01 15', N'antifreeze fluids other than those mentioned in 16 01 14'),
(N'16 01 16', N'tanks for liquefied gas'),
(N'16 01 17', N'ferrous metal'),
(N'16 01 18', N'non-ferrous metal'),
(N'16 01 19', N'Plastic'),
(N'16 01 20', N'Glass'),
(N'16 01 21*', N'hazardous components other than those mentioned in 16 01 07 to 16 01 11 and 16 01 13 and 16 01 14'),
(N'16 01 22', N'components not otherwise specified'),
(N'16 01 99', N'end-of-life vehicles from different means of transport (including off-road machinery) and wastes from dismantling of end-of-life vehicles and vehicle maintenance (except 13, 14, 16 06 and 16 08), wastes not otherwise specified'),
(N'16 02 09*', N'transformers and capacitors containing PCBs'),
(N'16 02 10*', N'discarded equipment containing or contaminated by PCBs other than those mentioned in 16 02 09'),
(N'16 02 11*', N'discarded equipment containing chlorofluorocarbons, HCFC, HFC'),
(N'16 02 12*', N'discarded equipment containing free asbestos'),
(N'16 02 13*', N'discarded equipment containing hazardous components (3) other than those mentioned in 16 02 09 to 16 02 12'),
(N'16 02 14', N'discarded equipment other than those mentioned in 16 02 09 to 16 02 13'),
(N'16 02 15*', N'hazardous components removed from discarded equipment'),
(N'16 02 16', N'components removed from discarded equipment other than those mentioned in 16 02 15'),
(N'16 03 03*', N'inorganic wastes containing hazardous substances'),
(N'16 03 04', N'inorganic wastes other than those mentioned in 16 03 03'),
(N'16 03 05*', N'organic wastes containing hazardous substances'),
(N'16 03 06', N'organic wastes other than those mentioned in 16 03 05'),
(N'16 03 07*', N'metallic mercury'),
(N'16 04 01*', N'waste ammunition'),
(N'16 04 02*', N'fireworks wastes'),
(N'16 04 03*', N'other waste explosives'),
(N'16 05 04*', N'gases in pressure containers (including halons) containing hazardous substances'),
(N'16 05 05', N'gases in pressure containers other than those mentioned in 16 05 04'),
(N'16 05 06*', N'laboratory chemicals, consisting of or containing hazardous substances, including mixtures of laboratory chemicals'),
(N'16 05 07*', N'discarded inorganic chemicals consisting of or containing hazardous substances'),
(N'16 05 08*', N'discarded organic chemicals consisting of or containing hazardous substances'),
(N'16 05 09', N'discarded chemicals other than those mentioned in 16 05 06, 16 05 07 or 16 05 08'),
(N'16 06 01*', N'lead batteries'),
(N'16 06 02*', N'Ni-Cd batteries'),
(N'16 06 03*', N'mercury-containing batteries'),
(N'16 06 04', N'alkaline batteries (except 16 06 03)'),
(N'16 06 05', N'other batteries and accumulators'),
(N'16 06 06*', N'separately collected electrolyte from batteries and accumulators'),
(N'16 07 08*', N'wastes containing oil'),
(N'16 07 09*', N'wastes containing other hazardous substances'),
(N'16 07 99', N'wastes from transport tank, storage tank and barrel cleaning (except 05 and 13), wastes not otherwise specified'),
(N'16 08 01', N'spent catalysts containing gold, silver, rhenium, rhodium, palladium, iridium or platinum (except 16 08 07)'),
(N'16 08 02*', N'spent catalysts containing hazardous transition metals or hazardous transition metal compounds'),
(N'16 08 03', N'spent catalysts containing transition metals or transition metal compounds not otherwise specified'),
(N'16 08 04', N'spent fluid catalytic cracking catalysts (except 16 08 07)'),
(N'16 08 05*', N'spent catalysts containing phosphoric acid'),
(N'16 08 06*', N'spent liquids used as catalysts'),
(N'16 08 07*', N'spent catalysts contaminated with hazardous substances'),
(N'16 09 01*', N'permanganates, for example potassium permanganate'),
(N'16 09 02*', N'chromates, for example potassium chromate, potassium or sodium dichromate'),
(N'16 09 03*', N'peroxides, for example hydrogen peroxide'),
(N'16 09 04*', N'oxidising substances, not otherwise specified'),
(N'16 10 01*', N'aqueous liquid wastes containing hazardous substances'),
(N'16 10 02', N'aqueous liquid wastes other than those mentioned in 16 10 01'),
(N'16 10 03*', N'aqueous concentrates containing hazardous substances'),
(N'16 10 04', N'aqueous concentrates other than those mentioned in 16 10 03'),
(N'16 11 01*', N'carbon-based linings and refractories from metallurgical processes containing hazardous substances'),
(N'16 11 02', N'carbon-based linings and refractories from metallurgical processes others than those mentioned in 16 11 01'),
(N'16 11 03*', N'other linings and refractories from metallurgical processes containing hazardous substances'),
(N'16 11 04', N'other linings and refractories from metallurgical processes other than those mentioned in 16 11 03'),
(N'16 11 05*', N'linings and refractories from non-metallurgical processes containing hazardous substances'),
(N'16 11 06', N'linings and refractories from non-metallurgical processes others than those mentioned in 16 11 05'),
(N'17 01 01', N'Concrete'),
(N'17 01 02', N'Bricks'),
(N'17 01 03', N'tiles and ceramics'),
(N'17 01 06*', N'mixtures of, or separate fractions of concrete, bricks, tiles and ceramics containing hazardous substances'),
(N'17 01 07', N'mixtures of concrete, bricks, tiles and ceramics other than those mentioned in 17 01 06'),
(N'17 02 01', N'Wood'),
(N'17 02 02', N'Glass'),
(N'17 02 03', N'Plastic'),
(N'17 02 04*', N'glass, plastic and wood containing or contaminated with hazardous substances'),
(N'17 03 01*', N'bituminous mixtures containing coal tar'),
(N'17 03 02', N'bituminous mixtures other than those mentioned in 17 03 01'),
(N'17 03 03*', N'coal tar and tarred products'),
(N'17 04 01', N'copper, bronze, brass'),
(N'17 04 02', N'Aluminium'),
(N'17 04 03', N'Lead'),
(N'17 04 04', N'Zinc'),
(N'17 04 05', N'iron and steel'),
(N'17 04 06', N'Tin'),
(N'17 04 07', N'mixed metals'),
(N'17 04 09*', N'metal waste contaminated with hazardous substances'),
(N'17 04 10*', N'cables containing oil, coal tar and other hazardous substances'),
(N'17 04 11', N'cables other than those mentioned in 17 04 10'),
(N'17 05 03*', N'soil and stones containing hazardous substances'),
(N'17 05 04', N'soil and stones other than those mentioned in 17 05 03'),
(N'17 05 05*', N'dredging spoil containing hazardous substances'),
(N'17 05 06', N'dredging spoil other than those mentioned in 17 05 05'),
(N'17 05 07*', N'track ballast containing hazardous substances'),
(N'17 05 08', N'track ballast other than those mentioned in 17 05 07'),
(N'17 06 01*', N'insulation materials containing asbestos'),
(N'17 06 03*', N'other insulation materials consisting of or containing hazardous substances'),
(N'17 06 04', N'insulation materials other than those mentioned in 17 06 01 and 17 06 03'),
(N'17 06 05*', N'construction materials containing asbestos'),
(N'17 08 01*', N'gypsum-based construction materials contaminated with hazardous substances'),
(N'17 08 02', N'gypsum-based construction materials other than those mentioned in 17 08 01'),
(N'17 09 01*', N'construction and demolition wastes containing mercury'),
(N'17 09 02*', N'construction and demolition wastes containing PCB (for example PCB-containing sealants, PCB-containing resin-based floorings, PCB-containing sealed glazing units, PCB-containing capacitors)'),
(N'17 09 03*', N'other construction and demolition wastes (including mixed wastes) containing hazardous substances'),
(N'17 09 04', N'mixed construction and demolition wastes other than those mentioned in 17 09 01, 17 09 02 and 17 09 03'),
(N'18 01 01', N'sharps (except 18 01 03)'),
(N'18 01 02', N'body parts and organs including blood bags and blood preserves (except 18 01 03)'),
(N'18 01 03*', N'wastes whose collection and disposal is subject to special requirements in order to prevent infection'),
(N'18 01 04', N'wastes whose collection and disposal is not subject to special requirements in order to prevent infection (for example dressings, plaster casts, linen, disposable clothing, diapers)'),
(N'18 01 06*', N'chemicals consisting of or containing hazardous substances'),
(N'18 01 07', N'chemicals other than those mentioned in 18 01 06'),
(N'18 01 08*', N'cytotoxic and cytostatic medicines'),
(N'18 01 09', N'medicines other than those mentioned in 18 01 08'),
(N'18 01 10*', N'amalgam waste from dental care'),
(N'18 02 01', N'sharps (except 18 02 02)'),
(N'18 02 02*', N'wastes whose collection and disposal is subject to special requirements in order to prevent infection'),
(N'18 02 03', N'wastes whose collection and disposal is not subject to special requirements in order to prevent infection'),
(N'18 02 05*', N'chemicals consisting of or containing hazardous substances'),
(N'18 02 06', N'chemicals other than those mentioned in 18 02 05'),
(N'18 02 07*', N'cytotoxic and cytostatic medicines'),
(N'18 02 08', N'medicines other than those mentioned in 18 02 07'),
(N'19 01 02', N'ferrous materials removed from bottom ash'),
(N'19 01 05*', N'filter cake from gas treatment'),
(N'19 01 06*', N'aqueous liquid wastes from gas treatment and other aqueous liquid wastes'),
(N'19 01 07*', N'solid wastes from gas treatment'),
(N'19 01 10*', N'spent activated carbon from flue-gas treatment'),
(N'19 01 11*', N'bottom ash and slag containing hazardous substances'),
(N'19 01 12', N'bottom ash and slag other than those mentioned in 19 01 11'),
(N'19 01 13*', N'fly ash containing hazardous substances'),
(N'19 01 14', N'fly ash other than those mentioned in 19 01 13'),
(N'19 01 15*', N'boiler dust containing hazardous substances'),
(N'19 01 16', N'boiler dust other than those mentioned in 19 01 15'),
(N'19 01 17*', N'pyrolysis wastes containing hazardous substances'),
(N'19 01 18', N'pyrolysis wastes other than those mentioned in 19 01 17'),
(N'19 01 19', N'sands from fluidised beds'),
(N'19 01 99', N'wastes from incineration or pyrolysis of waste, wastes not otherwise specified'),
(N'19 02 03', N'premixed wastes composed only of non-hazardous wastes'),
(N'19 02 04*', N'premixed wastes composed of at least one hazardous waste'),
(N'19 02 05*', N'sludges from physico/chemical treatment containing hazardous substances'),
(N'19 02 06', N'sludges from physico/chemical treatment other than those mentioned in 19 02 05'),
(N'19 02 07*', N'oil and concentrates from separation'),
(N'19 02 08*', N'liquid combustible wastes containing hazardous substances'),
(N'19 02 09*', N'solid combustible wastes containing hazardous substances'),
(N'19 02 10', N'combustible wastes other than those mentioned in 19 02 08 and 19 02 09'),
(N'19 02 11*', N'other wastes containing hazardous substances'),
(N'19 02 99', N'wastes from physico/chemical treatments of waste (including dechromatation, decyanidation, neutralisation), wastes not otherwise specified'),
(N'19 03 04*', N'wastes marked as hazardous, partly stabilised other than 19 03 08'),
(N'19 03 05', N'stabilised wastes other than those mentioned in 19 03 04'),
(N'19 03 06*', N'wastes marked as hazardous, solidified'),
(N'19 03 07', N'solidified wastes other than those mentioned in 19 03 06'),
(N'19 03 08*', N'partly stabilised mercury'),
(N'19 04 01', N'vitrified waste'),
(N'19 04 02*', N'fly ash and other flue-gas treatment wastes'),
(N'19 04 03*', N'non-vitrified solid phase'),
(N'19 04 04', N'aqueous liquid wastes from vitrified waste tempering'),
(N'19 05 01', N'non-composted fraction of municipal and similar wastes'),
(N'19 05 02', N'non-composted fraction of animal and vegetable waste'),
(N'19 05 03', N'off-specification compost'),
(N'19 05 99', N'wastes from aerobic treatment of solid wastes, wastes not otherwise specified'),
(N'19 06 03', N'liquor from anaerobic treatment of municipal waste'),
(N'19 06 04', N'digestate from anaerobic treatment of municipal waste'),
(N'19 06 05', N'liquor from anaerobic treatment of animal and vegetable waste'),
(N'19 06 06', N'digestate from anaerobic treatment of animal and vegetable waste'),
(N'19 06 99', N'wastes from anaerobic treatment of waste, wastes not otherwise specified'),
(N'19 07 02*', N'landfill leachate containing hazardous substances'),
(N'19 07 03', N'landfill leachate other than those mentioned in 19 07 02'),
(N'19 08 01', N'Screenings'),
(N'19 08 02', N'waste from desanding'),
(N'19 08 05', N'sludges from treatment of urban waste water'),
(N'19 08 06*', N'saturated or spent ion exchange resins'),
(N'19 08 07*', N'solutions and sludges from regeneration of ion exchangers'),
(N'19 08 08*', N'membrane system waste containing heavy metals'),
(N'19 08 09', N'grease and oil mixture from oil/water separation containing only edible oil and fats'),
(N'19 08 10*', N'grease and oil mixture from oil/water separation other than those mentioned in 19 08 09'),
(N'19 08 11*', N'sludges containing hazardous substances from biological treatment of industrial waste water'),
(N'19 08 12', N'sludges from biological treatment of industrial waste water other than those mentioned in 19 08 11'),
(N'19 08 13*', N'sludges containing hazardous substances from other treatment of industrial waste water'),
(N'19 08 14', N'sludges from other treatment of industrial waste water other than those mentioned in 19 08 13'),
(N'19 08 99', N'wastes from waste water treatment plants not otherwise specified, wastes not otherwise specified'),
(N'19 09 01', N'solid waste from primary filtration and screenings'),
(N'19 09 02', N'sludges from water clarification'),
(N'19 09 03', N'sludges from decarbonation'),
(N'19 09 04', N'spent activated carbon'),
(N'19 09 05', N'saturated or spent ion exchange resins'),
(N'19 09 06', N'solutions and sludges from regeneration of ion exchangers'),
(N'19 09 99', N'wastes from the preparation of water intended for human consumption or water for industrial use, wastes not otherwise specified'),
(N'19 10 01', N'iron and steel waste'),
(N'19 10 02', N'non-ferrous waste'),
(N'19 10 03*', N'fluff-light fraction and dust containing hazardous substances'),
(N'19 10 04', N'fluff-light fraction and dust other than those mentioned in 19 10 03'),
(N'19 10 05*', N'other fractions containing hazardous substances'),
(N'19 10 06', N'other fractions other than those mentioned in 19 10 05'),
(N'19 11 01*', N'spent filter clays'),
(N'19 11 02*', N'acid tars'),
(N'19 11 03*', N'aqueous liquid wastes'),
(N'19 11 04*', N'wastes from cleaning of fuel with bases'),
(N'19 11 05*', N'sludges from on-site effluent treatment containing hazardous substances'),
(N'19 11 06', N'sludges from on-site effluent treatment other than those mentioned in 19 11 05'),
(N'19 11 07*', N'wastes from flue-gas cleaning'),
(N'19 11 99', N'wastes from oil regeneration, wastes not otherwise specified'),
(N'19 12 01', N'paper and cardboard'),
(N'19 12 02', N'ferrous metal'),
(N'19 12 03', N'non-ferrous metal'),
(N'19 12 04', N'plastic and rubber'),
(N'19 12 05', N'Glass'),
(N'19 12 06*', N'wood containing hazardous substances'),
(N'19 12 07', N'wood other than that mentioned in 19 12 06'),
(N'19 12 08', N'Textiles'),
(N'19 12 09', N'minerals (for example sand, stones)'),
(N'19 12 10', N'combustible waste (refuse derived fuel)'),
(N'19 12 11*', N'other wastes (including mixtures of materials) from mechanical treatment of waste containing hazardous substances'),
(N'19 12 12', N'other wastes (including mixtures of materials) from mechanical treatment of wastes other than those mentioned in 19 12 11'),
(N'19 13 01*', N'solid wastes from soil remediation containing hazardous substances'),
(N'19 13 02', N'solid wastes from soil remediation other than those mentioned in 19 13 01'),
(N'19 13 03*', N'sludges from soil remediation containing hazardous substances'),
(N'19 13 04', N'sludges from soil remediation other than those mentioned in 19 13 03'),
(N'19 13 05*', N'sludges from groundwater remediation containing hazardous substances'),
(N'19 13 06', N'sludges from groundwater remediation other than those mentioned in 19 13 05'),
(N'19 13 07*', N'aqueous liquid wastes and aqueous concentrates from groundwater remediation containing hazardous substances'),
(N'19 13 08', N'aqueous liquid wastes and aqueous concentrates from groundwater remediation other than those mentioned in 19 13 07'),
(N'20 01 01', N'paper and cardboard'),
(N'20 01 02', N'Glass'),
(N'20 01 08', N'biodegradable kitchen and canteen waste'),
(N'20 01 10', N'Clothes'),
(N'20 01 11', N'Textiles'),
(N'20 01 13*', N'Solvents'),
(N'20 01 14*', N'Acids'),
(N'20 01 15*', N'Alkalines'),
(N'20 01 17*', N'Photochemicals'),
(N'20 01 19*', N'Pesticides'),
(N'20 01 21*', N'fluorescent tubes and other mercury-containing waste'),
(N'20 01 23*', N'discarded equipment containing chlorofluorocarbons'),
(N'20 01 25', N'edible oil and fat'),
(N'20 01 26*', N'oil and fat other than those mentioned in 20 01 25'),
(N'20 01 27*', N'paint, inks, adhesives and resins containing hazardous substances'),
(N'20 01 28', N'paint, inks, adhesives and resins other than those mentioned in 20 01 27'),
(N'20 01 29*', N'detergents containing hazardous substances'),
(N'20 01 30', N'detergents other than those mentioned in 20 01 29'),
(N'20 01 31*', N'cytotoxic and cytostatic medicines'),
(N'20 01 32', N'medicines other than those mentioned in 20 01 31'),
(N'20 01 33*', N'batteries and accumulators included in 16 06 01, 16 06 02 or 16 06 03 and unsorted batteries and accumulators containing these batteries'),
(N'20 01 34', N'batteries and accumulators other than those mentioned in 20 01 33'),
(N'20 01 35*', N'discarded electrical and electronic equipment other than those mentioned in 20 01 21 and 20 01 23 containing hazardous components (3)'),
(N'20 01 36', N'discarded electrical and electronic equipment other than those mentioned in 20 01 21, 20 01 23 and 20 01 35'),
(N'20 01 37*', N'wood containing hazardous substances'),
(N'20 01 38', N'wood other than that mentioned in 20 01 37'),
(N'20 01 39', N'Plastics'),
(N'20 01 40', N'Metals'),
(N'20 01 41', N'wastes from chimney sweeping'),
(N'20 01 99', N'separately collected fractions (except 15 01), other fractions not otherwise specified'),
(N'20 02 01', N'biodegradable waste'),
(N'20 02 02', N'soil and stones'),
(N'20 02 03', N'other non-biodegradable wastes'),
(N'20 03 01', N'mixed municipal waste'),
(N'20 03 02', N'waste from markets'),
(N'20 03 03', N'street-cleaning residues'),
(N'20 03 04', N'septic tank sludge'),
(N'20 03 06', N'waste from sewage cleaning'),
(N'20 03 07', N'bulky waste'),
(N'20 03 99', N'municipal wastes not otherwise specified');

print 'Updating descriptions';

UPDATE		WC

SET			WC.Description = EWC.Description

FROM		[Lookup].[WasteCode] AS WC

INNER JOIN	@EwcCodes AS EWC
ON			EWC.[Code] = WC.[Code]

WHERE		WC.CodeType = 3;

print 'Inserting missing data';

INSERT INTO		[Lookup].[WasteCode] (Id, Code, Description, CodeType)

SELECT			(SELECT Cast(Cast(Newid() AS BINARY(10)) + Cast(Getdate() AS BINARY(6)) AS UNIQUEIDENTIFIER)),
				EWC.Code,
				EWC.Description,
				3

FROM			@EwcCodes AS EWC

LEFT OUTER JOIN	[Lookup].[WasteCode] AS WC
ON				EWC.[Code] = WC.[Code] 

WHERE			WC.[Code] IS NULL;

print 'update complete';