GO

insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES ('E8295454-C5C2-47E0-A919-9B7501F64426','Not applicable','',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H1','Explosive',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H10','Iberation of toxic gases in contact with air or water',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H11','Oxic (delayed or chronic)',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H12','Cotoxic',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H13','Capable, by any means, after disposal of yielding another material, e.g., leachate, which possesses any of the characteristics listed above',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H3','Flammable liquids',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H4.1','Flammable solids',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H4.2','Substances or wastes liable to spontaneous combustion',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H4.3','Substances or wastes which, in contact with water, emit flammable gases',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H5.1','Oxidizing',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H5.2','Organic peroxides',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H6.1','Poisonous (acute)',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H6.2','Infectious substances',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'H8','Corrosive',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP1','Explosive',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP10','Toxic for reproduction',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP11','Mutagenic',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP12','Release of an acute toxic gas',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP13','Sensitising',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP15','Waste capable of exhibiting a hazardous property listed above not directly displayed by the original waste',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP2' ,'Oxidising',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP3' ,'Flammable',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP4','Irritant',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP5','Specific Target Organ Toxicity/Aspiration Toxicity',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP6','Acute Toxicity',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP7','Carcinogenic',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP8','Corrosive',5)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'HP9','Infectious',5)


GO