//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminImportAssessment.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DecisionControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecisionControllerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminImportAssessment.Controllers.DecisionControllerResources", typeof(DecisionControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision made date cannot be before the acknowledged on date.
        /// </summary>
        public static string ConsentedNotBeforeAcknowledged {
            get {
                return ResourceManager.GetString("ConsentedNotBeforeAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision made date cannot be in the future.
        /// </summary>
        public static string ConsentedNotInFuture {
            get {
                return ResourceManager.GetString("ConsentedNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid from date cannot be before the acknowledged on date.
        /// </summary>
        public static string ValidFromNotBeforeAcknowledged {
            get {
                return ResourceManager.GetString("ValidFromNotBeforeAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid from date cannot be in the future.
        /// </summary>
        public static string ValidFromNotInFuture {
            get {
                return ResourceManager.GetString("ValidFromNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This valid to date cannot be more than one calendar year away from the valid from date.
        /// </summary>
        public static string ValidFromNotPreconsented {
            get {
                return ResourceManager.GetString("ValidFromNotPreconsented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This valid to date cannot be more than three calendar years away from the valid from date.
        /// </summary>
        public static string ValidFromPreconsented {
            get {
                return ResourceManager.GetString("ValidFromPreconsented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid to date cannot be in the past or include today’s date.
        /// </summary>
        public static string ValidToMustBeInFuture {
            get {
                return ResourceManager.GetString("ValidToMustBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision made date cannot be before the notification received date.
        /// </summary>
        public static string WithdrawNotBeforeReceived {
            get {
                return ResourceManager.GetString("WithdrawNotBeforeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision made date cannot be in the future.
        /// </summary>
        public static string WithdrawNotInFuture {
            get {
                return ResourceManager.GetString("WithdrawNotInFuture", resourceCulture);
            }
        }
    }
}
