//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.Admin.Views.Worklist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.Admin.Views.Worklist.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement date.
        /// </summary>
        public static string AcknowledgementDate {
            get {
                return ResourceManager.GetString("AcknowledgementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consented date.
        /// </summary>
        public static string ConsentedDate {
            get {
                return ResourceManager.GetString("ConsentedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date acknowledged.
        /// </summary>
        public static string DateAcknowledged {
            get {
                return ResourceManager.GetString("DateAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date consented.
        /// </summary>
        public static string DateConsented {
            get {
                return ResourceManager.GetString("DateConsented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date picked up.
        /// </summary>
        public static string DatePickedUp {
            get {
                return ResourceManager.GetString("DatePickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date transmitted.
        /// </summary>
        public static string DateTransmitted {
            get {
                return ResourceManager.GetString("DateTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining.
        /// </summary>
        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision required.
        /// </summary>
        public static string DecisionRequired {
            get {
                return ResourceManager.GetString("DecisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial guarantee status.
        /// </summary>
        public static string FinancialGuaranteeStatus {
            get {
                return ResourceManager.GetString("FinancialGuaranteeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last action.
        /// </summary>
        public static string LastAction {
            get {
                return ResourceManager.GetString("LastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last comment.
        /// </summary>
        public static string LastComment {
            get {
                return ResourceManager.GetString("LastComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export notifications found matching the current filter..
        /// </summary>
        public static string NoExportNotificationsFoundDescription {
            get {
                return ResourceManager.GetString("NoExportNotificationsFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No import notifications found matching the current filter..
        /// </summary>
        public static string NoImportNotificationsFoundDescription {
            get {
                return ResourceManager.GetString("NoImportNotificationsFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification number.
        /// </summary>
        public static string NotificationNumber {
            get {
                return ResourceManager.GetString("NotificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status.
        /// </summary>
        public static string NotificationStatus {
            get {
                return ResourceManager.GetString("NotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifier.
        /// </summary>
        public static string Notifier {
            get {
                return ResourceManager.GetString("Notifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        public static string Officer {
            get {
                return ResourceManager.GetString("Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working days in assessment.
        /// </summary>
        public static string WorkingDaysInAssessment {
            get {
                return ResourceManager.GetString("WorkingDaysInAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklist.
        /// </summary>
        public static string Worklist {
            get {
                return ResourceManager.GetString("Worklist", resourceCulture);
            }
        }
    }
}
