//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.Facility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteOfTreatmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteOfTreatmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.Facility.SiteOfTreatmentResources", typeof(SiteOfTreatmentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual site of treatment?.
        /// </summary>
        public static string ActualSite {
            get {
                return ResourceManager.GetString("ActualSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to facilities.
        /// </summary>
        public static string BackToFacilities {
            get {
                return ResourceManager.GetString("BackToFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where will the waste be finally {0}.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any facilities to this notification. Please add a facility before selecting the site the waste will be finally {0}..
        /// </summary>
        public static string NoFacility {
            get {
                return ResourceManager.GetString("NoFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the actual {0}.
        /// </summary>
        public static string SiteRequired {
            get {
                return ResourceManager.GetString("SiteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of facilities for actual site of treatment.
        /// </summary>
        public static string TableTitle {
            get {
                return ResourceManager.GetString("TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual site of {0}.
        /// </summary>
        public static string ThActualSite {
            get {
                return ResourceManager.GetString("ThActualSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ThAddress {
            get {
                return ResourceManager.GetString("ThAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string ThOrgName {
            get {
                return ResourceManager.GetString("ThOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Of Treatment.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
