//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.ImportNotification.Views.Importer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.ImportNotification.Views.Importer.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter above registration number to enable &apos;Import name&apos; button..
        /// </summary>
        public static string ImpNameButtonHintMsg {
            get {
                return ResourceManager.GetString("ImpNameButtonHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import name.
        /// </summary>
        public static string ImportName {
            get {
                return ResourceManager.GetString("ImportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Company.
        /// </summary>
        public static string LimitedCompanyLabel {
            get {
                return ResourceManager.GetString("LimitedCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string OrganisationNameTitle {
            get {
                return ResourceManager.GetString("OrganisationNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string OrganisationSubtitle {
            get {
                return ResourceManager.GetString("OrganisationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation type.
        /// </summary>
        public static string OrganisationType {
            get {
                return ResourceManager.GetString("OrganisationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an organisation type.
        /// </summary>
        public static string OrganisationTypeRequired {
            get {
                return ResourceManager.GetString("OrganisationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help with appropriate naming conventions.
        /// </summary>
        public static string OrgHelpSummary {
            get {
                return ResourceManager.GetString("OrgHelpSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When inputting your organisation name, the following naming conventions should be used to minimise errors:.
        /// </summary>
        public static string OrgHelpSummaryDetailsHeader {
            get {
                return ResourceManager.GetString("OrgHelpSummaryDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name abbreviations should always be in uppercase with no full stops.
        /// </summary>
        public static string OrgHelpSummaryDetailsPoint1 {
            get {
                return ResourceManager.GetString("OrgHelpSummaryDetailsPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be no spaces either side of special characters, particularly at the end of the name.
        /// </summary>
        public static string OrgHelpSummaryDetailsPoint2 {
            get {
                return ResourceManager.GetString("OrgHelpSummaryDetailsPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be no full stops present.
        /// </summary>
        public static string OrgHelpSummaryDetailsPoint3 {
            get {
                return ResourceManager.GetString("OrgHelpSummaryDetailsPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Instead of &apos;a &amp; b materials&apos;, the name should be &apos;A&amp;B Materials&apos;.
        /// </summary>
        public static string OrgHelpSummaryDetailsPoint4 {
            get {
                return ResourceManager.GetString("OrgHelpSummaryDetailsPoint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &apos;Import name&apos; button to import the name from Companies House using the registration number. If no organisation name is found, please check your registration number and retry. If your Organisation name is not available, you may need to change the Company type and enter the name manually..
        /// </summary>
        public static string OrgHelpWithNamingDescription {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example &apos;A&amp;B Materials CD&apos;.
        /// </summary>
        public static string OrgNameHintMsgNonUK {
            get {
                return ResourceManager.GetString("OrgNameHintMsgNonUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example &apos;A&amp;B Materials&apos;.
        /// </summary>
        public static string OrgNameHintMsgUK {
            get {
                return ResourceManager.GetString("OrgNameHintMsgUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name your organisation trades under if different to your organisation name.
        /// </summary>
        public static string OrgTradingNameHint {
            get {
                return ResourceManager.GetString("OrgTradingNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string TabTitle {
            get {
                return ResourceManager.GetString("TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The importer - consignee.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
