GO

insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES ('88CF5FCD-3555-47D5-9C09-2243D7BC2CFC','Not applicable','',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'1','Explosives',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'2','Gases',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'2.1','Flammable gas',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'2.2','Non-flammable, non-toxic gas',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'2.3','Toxic gas',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'3','Flammable liquid',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'4','Flammable solids',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'4.1','Flammable solid',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'4.2','Spontaneously combustible substance',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'4.3','Substance which in contact with water emits flammable gas',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'5','Oxidising substances',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'5.1','Oxidising substance',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'5.2','Organic peroxide',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'6','Toxic substances',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'6.1','Toxic substance',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'6.2','Infectious substance',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'8','Corrosive substances',6)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'9','Miscellaneous dangerous goods',6)
GO