GO

insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES ('8D7C857B-9AD1-4C41-9C71-0AB82CC13FF8','Not applicable','',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y1','Clinical wastes from medical care in hospitals, medical centers and clinics',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y2','Wastes from the production and preparation of pharmaceutical products',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y3','Waste pharmaceuticals, drugs and medicines',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y4','Wastes from the production, formulation and use of biocides and phytopharmaceuticals',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y5','Wastes from the manufacture, formulation and use of wood preserving chemicals',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y6','Wastes from the production, formulation and use of organic solvents',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y7','Wastes from heat treatment and tempering operations containing cyanides',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y8','Waste mineral oils unfit for their originally intended use',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y9','Waste oils/water, hydrocarbons/water mixtures, emulsions',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y10','Waste substances and articles containing or contaminated with polychlorinated biphenyls (PCBs) and/or polychlorinated terphenyls (PCTs) and/or polybrominated biphenyls (PBBs)',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y11','Waste tarry residues arising from refining, distillation and any pyrolytic treatment',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y12','Wastes from production, formulation and use of inks, dyes, pigments, paints, lacquers, varnish',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y13','Wastes from production, formulation and use of resins, latex, plasticizers, glues/adhesives',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y14','Waste chemical substances arising from research and development or teaching activities which are not identified and/or are new and whose effects on man and/or the environment are not known',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y15','Wastes of an explosive nature not subject to other legislation',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y16','Wastes from production, formulation and use of photographic chemicals and processing materials',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y17','Wastes resulting from surface treatment of metals and plastics',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y18','Residues arising from industrial waste disposal operations',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y19','Metal carbonyls',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y20','Beryllium; beryllium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y21','Hexavalent chromium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y22','Copper compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y23','Zinc compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y24','Arsenic; arsenic compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y25','Selenium; selenium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y26','Cadmium; cadmium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y27','Antimony; antimony compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y28','Tellurium; tellurium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y29','Mercury; mercury compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y30','Thallium; thallium compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y31','Lead; lead compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y32','Inorganic fluorine compounds excluding calcium fluoride',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y33','Inorganic cyanides',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y34','Acidic solutions or acids in solid form',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y35','Basic solutions or bases in solid form',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y36','Asbestos (dust and fibres)',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y37','Organic phosphorus compounds',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y38','Organic cyanides',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y39','Phenols; phenol compounds including chlorophenols',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y40','Ethers',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y41','Halogenated organic solvents',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y42','Organic solvents excluding halogenated solvents',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y43','Any congenor of polychlorinated dibenzo-furan',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y44','Any congenor of polychlorinated dibenzo-p-dioxin',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y45','Organohalogen compounds other than substances referred to in this Annex (e.g. Y39, Y41, Y42, Y43, Y44)',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y46','Wastes collected from households',4)
insert into [Lookup].[WasteCode]([Id],[Code],[Description],[CodeType]) VALUES (newid(),'Y47','Residues arising from the incineration of household wastes',4)

GO