IF OBJECT_ID('[Reports].[uspUpdateReportCache]') IS NULL
    EXEC('CREATE PROCEDURE [Reports].[uspUpdateReportCache] AS SET NOCOUNT ON;')
GO

ALTER PROCEDURE [Reports].[uspUpdateReportCache]
AS
BEGIN

    DELETE FROM [Reports].[FreedomOfInformationCache];
    DELETE FROM [Reports].[NotificationShipmentDataMissingShipmentsCache];

    INSERT INTO [Reports].[FreedomOfInformationCache] (
           [NotificationNumber]
          ,[ImportOrExport]
          ,[IsInterim]
          ,[ReceivedDate]
          ,[CompetentAuthorityId]
          ,[NotifierName]
          ,[NotifierAddress]
          ,[NotifierPostalCode]
          ,[ProducerName]
          ,[ProducerAddress]
          ,[ProducerPostalCode]
          ,[PointOfExport]
          ,[PointOfEntry]
          ,[ImportCountryName]
          ,[ChemicalCompositionTypeId]
          ,[NameOfWaste]
          ,[EWC]
          ,[YCode]
          ,[HCode]
          ,[OperationCodes]
          ,[ImporterName]
          ,[ImporterAddress]
          ,[ImporterPostalCode]
          ,[FacilityName]
          ,[FacilityAddress]
          ,[FacilityPostalCode]
          ,[IntendedQuantity]
          ,[IntendedQuantityUnit]
          ,[IntendedQuantityUnitId]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[LocalArea]
          ,[MovementNumber]
          ,[MovementReceivedDate]
          ,[MovementCompletedDate]
          ,[MovementQuantityReceviedUnitId]
          ,[MovementQuantityReceived] )
    SELECT [NotificationNumber]
          ,[ImportOrExport]
          ,[IsInterim]
          ,[ReceivedDate]
          ,[CompetentAuthorityId]
          ,[NotifierName]
          ,[NotifierAddress]
          ,[NotifierPostalCode]
          ,[ProducerName]
          ,[ProducerAddress]
          ,[ProducerPostalCode]
          ,[PointOfExport]
          ,[PointOfEntry]
          ,[ImportCountryName]
          ,[ChemicalCompositionTypeId]
          ,[NameOfWaste]
          ,[EWC]
          ,[YCode]
          ,[HCode]
          ,[OperationCodes]
          ,[ImporterName]
          ,[ImporterAddress]
          ,[ImporterPostalCode]
          ,[FacilityName]
          ,[FacilityAddress]
          ,[FacilityPostalCode]
          ,[IntendedQuantity]
          ,[IntendedQuantityUnit]
          ,[IntendedQuantityUnitId]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[LocalArea]
          ,[MovementNumber]
          ,[MovementReceivedDate]
          ,[MovementCompletedDate]
          ,[MovementQuantityReceviedUnitId]
          ,[MovementQuantityReceived]
      FROM [Reports].[FreedomOfInformation];

    INSERT INTO [Reports].[NotificationShipmentDataMissingShipmentsCache] (
           [NotificationId]
          ,[NotificationNumber]
          ,[CompetentAuthorityId]
          ,[Exporter]
          ,[Importer]
          ,[Facility]
          ,[ShipmentNumber]
          ,[ActualDateOfShipment]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[PrenotificationDate]
          ,[ReceivedDate]
          ,[CompletedDate]
          ,[QuantityReceived]
          ,[QuantityReceivedUnit]
          ,[QuantityReceivedUnitId]
          ,[ChemicalComposition]
          ,[LocalArea]
          ,[TotalQuantity]
          ,[TotalQuantityUnits]
          ,[TotalQuantityUnitsId]
          ,[EntryPort]
          ,[DestinationCountry]
          ,[ExitPort]
          ,[OriginatingCountry]
          ,[Status]
          ,[NotificationReceivedDate]
          ,[EwcCodes] )
    SELECT [NotificationId]
          ,[NotificationNumber]
          ,[CompetentAuthorityId]
          ,[Exporter]
          ,[Importer]
          ,[Facility]
          ,[ShipmentNumber]
          ,[ActualDateOfShipment]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[PrenotificationDate]
          ,[ReceivedDate]
          ,[CompletedDate]
          ,[QuantityReceived]
          ,[QuantityReceivedUnit]
          ,[QuantityReceivedUnitId]
          ,[ChemicalComposition]
          ,[LocalArea]
          ,[TotalQuantity]
          ,[TotalQuantityUnits]
          ,[TotalQuantityUnitsId]
          ,[EntryPort]
          ,[DestinationCountry]
          ,[ExitPort]
          ,[OriginatingCountry]
          ,[Status]
          ,[NotificationReceivedDate]
          ,[EwcCodes]
      FROM [Reports].[NotificationShipmentDataMissingShipments]

END
GO