IF OBJECT_ID('[Reports].[uspUpdateReportCache]') IS NULL
    EXEC('CREATE PROCEDURE [Reports].[uspUpdateReportCache] AS SET NOCOUNT ON;')
GO

ALTER PROCEDURE [Reports].[uspUpdateReportCache]
AS
BEGIN

    DELETE FROM [Reports].[FreedomOfInformationCache];
    DELETE FROM [Reports].[ShipmentsCache];

    INSERT INTO [Reports].[FreedomOfInformationCache] (
           [NotificationNumber]
          ,[ImportOrExport]
          ,[IsInterim]
          ,[ReceivedDate]
          ,[CompetentAuthorityId]
          ,[NotifierName]
          ,[NotifierAddress]
          ,[NotifierPostalCode]
          ,[ProducerName]
          ,[ProducerAddress]
          ,[ProducerPostalCode]
          ,[PointOfExport]
          ,[PointOfEntry]
          ,[ImportCountryName]
          ,[ChemicalCompositionTypeId]
          ,[NameOfWaste]
          ,[EWC]
          ,[YCode]
          ,[HCode]
          ,[OperationCodes]
          ,[ImporterName]
          ,[ImporterAddress]
          ,[ImporterPostalCode]
          ,[FacilityName]
          ,[FacilityAddress]
          ,[FacilityPostalCode]
          ,[IntendedQuantity]
          ,[IntendedQuantityUnit]
          ,[IntendedQuantityUnitId]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[LocalArea]
          ,[MovementNumber]
          ,[MovementReceivedDate]
          ,[MovementCompletedDate]
          ,[MovementQuantityReceviedUnitId]
          ,[MovementQuantityReceived]
          ,[BaselOecdCode]
          ,[ExportCountryName]
		  ,[NotifierType]
		  ,[NotifierContactName]
		  ,[NotifierContactEmail]
		  ,[ProducerType]
		  ,[ProducerContactEmail]
		  ,[TransitStates]
		  ,[ImporterType]
		  ,[ImporterContactName]
		  ,[ImporterContactEmail]
		  ,[NotificationStatus]
          ,[NotificationStatusAtFileClosed]
		  ,[DecisionRequiredByDate]
		  ,[IsFinancialGuaranteeApproved]
		  ,[FileClosedDate]
		  ,[TechnologyEmployed]
		  ,[ActualDate]
		  ,[AcknowledgedDate]
		  ,[ObjectionDate]
		  ,[WithdrawnDate]
		  ,[SiteOfExportName]
		  ,[Officer] )
    SELECT [NotificationNumber]
          ,[ImportOrExport]
          ,[IsInterim]
          ,[ReceivedDate]
          ,[CompetentAuthorityId]
          ,[NotifierName]
          ,[NotifierAddress]
          ,[NotifierPostalCode]
          ,[ProducerName]
          ,[ProducerAddress]
          ,[ProducerPostalCode]
          ,[PointOfExport]
          ,[PointOfEntry]
          ,[ImportCountryName]
          ,[ChemicalCompositionTypeId]
          ,[NameOfWaste]
          ,[EWC]
          ,[YCode]
          ,[HCode]
          ,[OperationCodes]
          ,[ImporterName]
          ,[ImporterAddress]
          ,[ImporterPostalCode]
          ,[FacilityName]
          ,[FacilityAddress]
          ,[FacilityPostalCode]
          ,[IntendedQuantity]
          ,[IntendedQuantityUnit]
          ,[IntendedQuantityUnitId]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[LocalArea]
          ,[MovementNumber]
          ,[MovementReceivedDate]
          ,[MovementCompletedDate]
          ,[MovementQuantityReceviedUnitId]
          ,[MovementQuantityReceived]
          ,[BaselOecdCode]
          ,[ExportCountryName]
		  ,[NotifierType]
		  ,[NotifierContactName]
		  ,[NotifierContactEmail]
		  ,[ProducerType]
		  ,[ProducerContactEmail]
		  ,[TransitStates]
		  ,[ImporterType]
		  ,[ImporterContactName]
		  ,[ImporterContactEmail]
		  ,[NotificationStatus]
          ,[NotificationStatusAtFileClosed]
		  ,[DecisionRequiredByDate]
		  ,[IsFinancialGuaranteeApproved]
		  ,[FileClosedDate]
		  ,[TechnologyEmployed]
		  ,[ActualDate]
		  ,[AcknowledgedDate]
		  ,[ObjectionDate]
		  ,[WithdrawnDate]
		  ,[SiteOfExportName]
		  ,[Officer]
      FROM [Reports].[FreedomOfInformation];

    INSERT INTO [Reports].[ShipmentsCache] (
           [NotificationId]
          ,[NotificationNumber]
          ,[CompetentAuthorityId]
          ,[Exporter]
          ,[NotifierCompanyType]
          ,[Importer]
          ,[ConsigneeCompanyType]
          ,[Facility]
          ,[FacilityCompanyType]
          ,[ShipmentNumber]
          ,[ActualDateOfShipment]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[PrenotificationDate]
          ,[ReceivedDate]
          ,[CompletedDate]
          ,[QuantityReceived]
          ,[QuantityReceivedUnit]
          ,[QuantityReceivedUnitId]
          ,[ChemicalCompositionTypeId]
          ,[ChemicalComposition]
          ,[LocalArea]
          ,[TotalQuantity]
          ,[TotalQuantityUnits]
          ,[TotalQuantityUnitsId]
          ,[EntryPort]
          ,[DestinationCountry]
          ,[ExitPort]
          ,[OriginatingCountry]
          ,[Status]
          ,[NotificationReceivedDate]
          ,[EwcCodes]
          ,[ImportOrExport]
          ,[BaselOecdCode]
          ,[OperationCodes]
          ,[YCode]
          ,[HCode]
          ,[UNClass]
		  ,[SiteOfExportName]
          ,[RejectedQuantity]
		  ,[RejectedShipmentDate] 
          ,[RejectedReason]
          ,[ActionedByExternalUser])
    SELECT [NotificationId]
          ,[NotificationNumber]
          ,[CompetentAuthorityId]
          ,[Exporter]
          ,[NotifierCompanyType]
          ,[Importer]
		  ,[ConsigneeCompanyType]
          ,[Facility]
		  ,[FacilityCompanyType]
          ,[ShipmentNumber]
          ,[ActualDateOfShipment]
          ,[ConsentFrom]
          ,[ConsentTo]
          ,[PrenotificationDate]
          ,[ReceivedDate]
          ,[CompletedDate]
          ,[QuantityReceived]
          ,[QuantityReceivedUnit]
          ,[QuantityReceivedUnitId]
          ,[ChemicalCompositionTypeId]
          ,[ChemicalComposition]
          ,[LocalArea]
          ,[TotalQuantity]
          ,[TotalQuantityUnits]
          ,[TotalQuantityUnitsId]
          ,[EntryPort]
          ,[DestinationCountry]
          ,[ExitPort]
          ,[OriginatingCountry]
          ,[Status]
          ,[NotificationReceivedDate]
          ,[EwcCodes]
          ,[ImportOrExport]
          ,[BaselOecdCode]
          ,[OperationCodes]
          ,[YCode]
          ,[HCode]
          ,[UNClass]
		  ,[SiteOfExportName]
          ,[RejectedQuantity]
		  ,[RejectedShipmentDate]
          ,[RejectedReason]
          ,[ActionedByExternalUser]
      FROM [Reports].[Shipments];

	--Update the ActionedByExternalUser, this is Y if any MovementAudit action has been carried out by an external user.
	Select ma.NotificationId, ma.Shipmentnumber INTO [#MovementAuditExternalUserTempTable]
	from [Notification].[MovementAudit] ma
	Where ma.[Type] IN (1, 3, 4, 5)
	AND ma.UserId NOT IN (select UserId from [Person].[InternalUser])
	Group by ma.NotificationId, ma.ShipmentNumber

	update sc 
	SET sc.ActionedByExternalUser = 'Y'
	FROM [Reports].[ShipmentsCache] sc
	INNER JOIN [#MovementAuditExternalUserTempTable] MA
	ON MA.NotificationId = sc.NotificationId AND Ma.ShipmentNumber = sc.ShipmentNumber

	DROP TABLE [#MovementAuditExternalUserTempTable];

	DELETE FROM [Reports].[ProducerCache];

	INSERT INTO [Reports].[ProducerCache](
			[NotificationNumber] 
			,[CompetentAuthorityId] 
			,[NotifierName] 
			,[ProducerName] 
			,[ProducerAddress1] 
			,[ProducerAddress2] 
			,[ProducerTownOrCity] 
			,[ProducerPostCode] 
			,[SiteOfExport] 
			,[LocalArea] 
			,[WasteType] 
			,[NotificationStatus]
			,[ConsigneeName] 
			,[ConsentFrom] 
			,[ConsentTo] 
			,[NotificationReceivedDate] 
			,[MovementReceivedDate] 
			,[MovementCompletedDate] 
			,[EwcCode] 
			,[YCode] 
			,[PointOfExit] 
			,[PointOfEntry] 
			,[ExportCountryName] 
			,[ImportCountryName] 
			,[SiteOfExportName] 
			,[FacilityName] )
    SELECT DISTINCT p.* FROM (
        SELECT [NotificationNumber] 
		        ,[CompetentAuthorityId] 
		        ,[NotifierName] 
		        ,[ProducerName] 
		        ,[ProducerAddress1] 
		        ,[ProducerAddress2] 
		        ,[ProducerTownOrCity] 
		        ,[ProducerPostCode] 
		        ,[SiteOfExport] 
		        ,[LocalArea] 
		        ,[WasteType] 
		        ,[NotificationStatus]
		        ,[ConsigneeName] 
		        ,[ConsentFrom] 
		        ,[ConsentTo] 
		        ,[NotificationReceivedDate] 
		        ,[MovementReceivedDate] 
		        ,[MovementCompletedDate] 
		        ,[EwcCode] 
		        ,[YCode] 
		        ,[PointOfExit] 
		        ,[PointOfEntry] 
		        ,[ExportCountryName] 
		        ,[ImportCountryName] 
		        ,[SiteOfExportName] 
		        ,[FacilityName] 
        FROM [Reports].[Producers]
    ) p

END
GO
