//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminExportAssessment.Views.MarkAsInterim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminExportAssessment.Views.MarkAsInterim.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set as interim unless the notification is &quot;in assessment&quot;.
        /// </summary>
        public static string CantSetInterim {
            get {
                return ResourceManager.GetString("CantSetInterim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interim.
        /// </summary>
        public static string Interim {
            get {
                return ResourceManager.GetString("Interim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification is marked as interim.
        /// </summary>
        public static string MarkedAsInterim {
            get {
                return ResourceManager.GetString("MarkedAsInterim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification is marked as non-interim.
        /// </summary>
        public static string MarkedAsNonInterim {
            get {
                return ResourceManager.GetString("MarkedAsNonInterim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-interim.
        /// </summary>
        public static string NonInterim {
            get {
                return ResourceManager.GetString("NonInterim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this an interim or non-interim notification?.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is only possible to change the interim status of notifications that have the status:.
        /// </summary>
        public static string StatusErrorMessage {
            get {
                return ResourceManager.GetString("StatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This notification has the status.
        /// </summary>
        public static string ThisStatus {
            get {
                return ResourceManager.GetString("ThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change interim status.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
