//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.UpdateHistory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.UpdateHistory.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Day&apos; field.
        /// </summary>
        public static string DayError {
            get {
                return ResourceManager.GetString("DayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the start date for your search.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The from date must be before the to date.
        /// </summary>
        public static string FromDateAfterToDate {
            get {
                return ResourceManager.GetString("FromDateAfterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid from date.
        /// </summary>
        public static string FromValid {
            get {
                return ResourceManager.GetString("FromValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Month&apos; field.
        /// </summary>
        public static string MonthError {
            get {
                return ResourceManager.GetString("MonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Update History Search Results.
        /// </summary>
        public static string TableCaption {
            get {
                return ResourceManager.GetString("TableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification update history.
        /// </summary>
        public static string TabTitle {
            get {
                return ResourceManager.GetString("TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ThDate {
            get {
                return ResourceManager.GetString("ThDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Change.
        /// </summary>
        public static string ThInformationChange {
            get {
                return ResourceManager.GetString("ThInformationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ThName {
            get {
                return ResourceManager.GetString("ThName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ThTime {
            get {
                return ResourceManager.GetString("ThTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Change.
        /// </summary>
        public static string ThTypeOfChange {
            get {
                return ResourceManager.GetString("ThTypeOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification update history.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Update History Search Results.
        /// </summary>
        public static string TitleNotificationUpdateHistorySearchResults {
            get {
                return ResourceManager.GetString("TitleNotificationUpdateHistorySearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the end date for your search.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid to date.
        /// </summary>
        public static string ToValid {
            get {
                return ResourceManager.GetString("ToValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information changes reflect the changes made by officers and administrators..
        /// </summary>
        public static string UpdateHistoryInfo {
            get {
                return ResourceManager.GetString("UpdateHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number in the &apos;Year&apos; field.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
