//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.RequestHandlers.ImportNotification.Validate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipmentValidatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentValidatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.RequestHandlers.ImportNotification.Validate.ShipmentValidatorResources", typeof(ShipmentValidatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter an end date that is after the entered start date.
        /// </summary>
        public static string EndDateAfterStartDate {
            get {
                return ResourceManager.GetString("EndDateAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter an end date that is within the allowed range.
        /// </summary>
        public static string EndDateInConsentPeriod {
            get {
                return ResourceManager.GetString("EndDateInConsentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter an intended shipment range end date.
        /// </summary>
        public static string EndDateNotNull {
            get {
                return ResourceManager.GetString("EndDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter actual quantity.
        /// </summary>
        public static string QuantityNotNull {
            get {
                return ResourceManager.GetString("QuantityNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter a valid quantity.
        /// </summary>
        public static string QuantityPositive {
            get {
                return ResourceManager.GetString("QuantityPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter a start date that is before the entered end date.
        /// </summary>
        public static string StartDateBeforeEndDate {
            get {
                return ResourceManager.GetString("StartDateBeforeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter an intended shipment range start date.
        /// </summary>
        public static string StartDateNotNull {
            get {
                return ResourceManager.GetString("StartDateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter the total number of shipments.
        /// </summary>
        public static string TotalShipmentsNotNull {
            get {
                return ResourceManager.GetString("TotalShipmentsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter a valid total number of shipments.
        /// </summary>
        public static string TotalShipmentsPositive {
            get {
                return ResourceManager.GetString("TotalShipmentsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a unit for the quantity.
        /// </summary>
        public static string UnitNotNull {
            get {
                return ResourceManager.GetString("UnitNotNull", resourceCulture);
            }
        }
    }
}
