//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.RequestHandlers.ImportNotification.Validate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateOfImportValidatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateOfImportValidatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.RequestHandlers.ImportNotification.Validate.StateOfImportValidatorResource" +
                            "s", typeof(StateOfImportValidatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select an entry point in the UK.
        /// </summary>
        public static string ImportEntryPointInUK {
            get {
                return ResourceManager.GetString("ImportEntryPointInUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select the entry point.
        /// </summary>
        public static string ImportEntryPointNotEmpty {
            get {
                return ResourceManager.GetString("ImportEntryPointNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a competent authority that is in the UK.
        /// </summary>
        public static string StateOfImportCompetentAuthorityInUK {
            get {
                return ResourceManager.GetString("StateOfImportCompetentAuthorityInUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select the competent authority.
        /// </summary>
        public static string StateOfImportCompetentAuthorityNotEmpty {
            get {
                return ResourceManager.GetString("StateOfImportCompetentAuthorityNotEmpty", resourceCulture);
            }
        }
    }
}
