//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.RequestHandlers.ImportNotification.Validate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransitStateValidatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransitStateValidatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.RequestHandlers.ImportNotification.Validate.TransitStateValidatorResources" +
                            "", typeof(TransitStateValidatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select the transit competent authority for the selected country.
        /// </summary>
        public static string CompetentAuthorityMustBeSelectedCountry {
            get {
                return ResourceManager.GetString("CompetentAuthorityMustBeSelectedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a transit state country.
        /// </summary>
        public static string CountryNotNull {
            get {
                return ResourceManager.GetString("CountryNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select an entry point in the selected country.
        /// </summary>
        public static string EntryPointMustBeSelectedCountry {
            get {
                return ResourceManager.GetString("EntryPointMustBeSelectedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select an exit point in the selected country.
        /// </summary>
        public static string ExitPointMustBeSelectedCountry {
            get {
                return ResourceManager.GetString("ExitPointMustBeSelectedCountry", resourceCulture);
            }
        }
    }
}
