//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.ShareNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareNotificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareNotificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.ShareNotification.ShareNotificatio" +
                            "nResources", typeof(ShareNotificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add email.
        /// </summary>
        public static string AddSharedUser {
            get {
                return ResourceManager.GetString("AddSharedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting shared users.
        /// </summary>
        public static string AwaitingSharedUsers {
            get {
                return ResourceManager.GetString("AwaitingSharedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to share access.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chosen shared users.
        /// </summary>
        public static string ChosenSharedUsers {
            get {
                return ResourceManager.GetString("ChosenSharedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is your responsibility as the owner to advise the user you want to share this notification with; what they can, and can&apos;t do on this notification once shared..
        /// </summary>
        public static string ConfirmResponsibility {
            get {
                return ResourceManager.GetString("ConfirmResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the email address that was used to register their account and they enter when logging into the service. If they are not registered to use IWS Online, they will need to do this first..
        /// </summary>
        public static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the e-mail addresses of other users you want to share this notification with..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to notification options.
        /// </summary>
        public static string NotificationOption {
            get {
                return ResourceManager.GetString("NotificationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared User.
        /// </summary>
        public static string SharedUser {
            get {
                return ResourceManager.GetString("SharedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Users.
        /// </summary>
        public static string SharedUserTableTitle {
            get {
                return ResourceManager.GetString("SharedUserTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This notification will be shared with:.
        /// </summary>
        public static string ShareNotificationConfirmShareUsers {
            get {
                return ResourceManager.GetString("ShareNotificationConfirmShareUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to share notification {notification} to these users?.
        /// </summary>
        public static string ShareNotificationConfirmTitle {
            get {
                return ResourceManager.GetString("ShareNotificationConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this notification with other users.
        /// </summary>
        public static string ShareNotificationTitle {
            get {
                return ResourceManager.GetString("ShareNotificationTitle", resourceCulture);
            }
        }
    }
}
