//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.ViewModels.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.ViewModels.Shared.BusinessResources", typeof(BusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The additional registration number cannot be greater than 100 characters.
        /// </summary>
        public static string AdditionalRegistrationNumberMaxLength {
            get {
                return ResourceManager.GetString("AdditionalRegistrationNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional registration number.
        /// </summary>
        public static string AdditionalRegNumber {
            get {
                return ResourceManager.GetString("AdditionalRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of organisation.
        /// </summary>
        public static string BusinessTypeHeader {
            get {
                return ResourceManager.GetString("BusinessTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies House number.
        /// </summary>
        public static string CompaniesHouseNumber {
            get {
                return ResourceManager.GetString("CompaniesHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Companies House number is on your organisation&apos;s certificate of incorporation. You can also get the number from your organisation&apos;s accountant or accounts department..
        /// </summary>
        public static string CompanyHouseDescription {
            get {
                return ResourceManager.GetString("CompanyHouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies house number is required.
        /// </summary>
        public static string CompanyHouseRequired {
            get {
                return ResourceManager.GetString("CompanyHouseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an organisation type and enter a registration number. If none of these options apply, select &quot;Other&quot; and add details..
        /// </summary>
        public static string FormHint {
            get {
                return ResourceManager.GetString("FormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an organisation type and enter a registration number if required. If none of these options apply, select &quot;Other&quot; and add details..
        /// </summary>
        public static string FormHintProducer {
            get {
                return ResourceManager.GetString("FormHintProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When inputting your organisation name, the following naming conventions should be used to minimise errors:.
        /// </summary>
        public static string OrgHelpWithNamingContent1 {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name abbreviations should always be in uppercase with no full stops.
        /// </summary>
        public static string OrgHelpWithNamingContent2 {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be no spaces either side of special characters, particularly at the end of the name.
        /// </summary>
        public static string OrgHelpWithNamingContent3 {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company suffixes should always be uppercase with no full stops (excluding GmbH).
        /// </summary>
        public static string OrgHelpWithNamingContent4NonUk {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent4NonUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be no full stops present.
        /// </summary>
        public static string OrgHelpWithNamingContent4Uk {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent4Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Instead of &apos;A &amp; b Materials c.d.&apos; the name should be &apos;A&amp;B Materials CD&apos;.
        /// </summary>
        public static string OrgHelpWithNamingContent5NonUk {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent5NonUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Instead of &apos;a &amp; b materials&apos;, the name should be &apos;A&amp;B Materials&apos;.
        /// </summary>
        public static string OrgHelpWithNamingContent5Uk {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingContent5Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &apos;Import name&apos; button to import the name from Companies House using the registration number. If no organisation name is found, please check your registration number and retry. If your Organisation name is not available, you may need to change the Company type and enter the name manually..
        /// </summary>
        public static string OrgHelpWithNamingDescription {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help with appropriate naming conventions.
        /// </summary>
        public static string OrgHelpWithNamingTitle {
            get {
                return ResourceManager.GetString("OrgHelpWithNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string OrgName {
            get {
                return ResourceManager.GetString("OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string OrgNameHeader {
            get {
                return ResourceManager.GetString("OrgNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example &apos;A&amp;B Materials&apos;.
        /// </summary>
        public static string OrgNameHint {
            get {
                return ResourceManager.GetString("OrgNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the organisation&apos;s name.
        /// </summary>
        public static string OrgNameRequired {
            get {
                return ResourceManager.GetString("OrgNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Trading as&apos; name.
        /// </summary>
        public static string OrgTradingName {
            get {
                return ResourceManager.GetString("OrgTradingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name your organisation trades under if different to your organisation name.
        /// </summary>
        public static string OrgTradingNameHint {
            get {
                return ResourceManager.GetString("OrgTradingNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation type.
        /// </summary>
        public static string OrgType {
            get {
                return ResourceManager.GetString("OrgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the type of organisation.
        /// </summary>
        public static string OrgTypeRequired {
            get {
                return ResourceManager.GetString("OrgTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation type.
        /// </summary>
        public static string OtherOrgType {
            get {
                return ResourceManager.GetString("OtherOrgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe this type of organisation.
        /// </summary>
        public static string OtherOrgTypeRequired {
            get {
                return ResourceManager.GetString("OtherOrgTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership registration number is required.
        /// </summary>
        public static string PartnershipRegNoRequired {
            get {
                return ResourceManager.GetString("PartnershipRegNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be the registration number of the company in the country in which they are registered..
        /// </summary>
        public static string RegistrationNumberHintNonUK {
            get {
                return ResourceManager.GetString("RegistrationNumberHintNonUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 8-character code as documented by Companies House..
        /// </summary>
        public static string RegistrationNumberHintUK {
            get {
                return ResourceManager.GetString("RegistrationNumberHintUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration number cannot be greater than 100 characters.
        /// </summary>
        public static string RegistrationNumberMaxLength {
            get {
                return ResourceManager.GetString("RegistrationNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the registration number.
        /// </summary>
        public static string RegNumberRequired {
            get {
                return ResourceManager.GetString("RegNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Trader registration number is required.
        /// </summary>
        public static string SoleTraderRegNoRequired {
            get {
                return ResourceManager.GetString("SoleTraderRegNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where can I find my Companies House number?.
        /// </summary>
        public static string WhereToFindCompanyHouse {
            get {
                return ResourceManager.GetString("WhereToFindCompanyHouse", resourceCulture);
            }
        }
    }
}
