//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.NotificationApplication.Views.ChemicalComposition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WoodContinuedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WoodContinuedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.NotificationApplication.Views.ChemicalComposition.WoodContinuedR" +
                            "esources", typeof(WoodContinuedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will provide further details in an annex when I submit my notification..
        /// </summary>
        public static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information.
        /// </summary>
        public static string FurtherInformation {
            get {
                return ResourceManager.GetString("FurtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please limit your answer to 256 characters.
        /// </summary>
        public static string FurtherInformationHint {
            get {
                return ResourceManager.GetString("FurtherInformationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the chemical composition of the waste? (continued).
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any other relevant information (optional).
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the chemical composition of the waste?.
        /// </summary>
        public static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration levels of the constituents present in the waste. Enter minimum and maximum as a weight by weight percentage (%), you can enter NA where not applicable..
        /// </summary>
        public static string Header3Description {
            get {
                return ResourceManager.GetString("Header3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max %.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  maximum concentration.
        /// </summary>
        public static string MaxConcentration {
            get {
                return ResourceManager.GetString("MaxConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min %.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minimum concentration.
        /// </summary>
        public static string MinConcentration {
            get {
                return ResourceManager.GetString("MinConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 of 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical composition of waste continued.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
