//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Iws.Web.Areas.AdminExportAssessment.ViewModels.Decision {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationAssessmentDecisionViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationAssessmentDecisionViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Iws.Web.Areas.AdminExportAssessment.ViewModels.Decision.NotificationAssessment" +
                            "DecisionViewModelResources", typeof(NotificationAssessmentDecisionViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent valid from date must not be in the past.
        /// </summary>
        public static string ConsentDateNotPast {
            get {
                return ResourceManager.GetString("ConsentDateNotPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consented date is required.
        /// </summary>
        public static string ConsentedDateRequired {
            get {
                return ResourceManager.GetString("ConsentedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent valid from date must be before the consent valid to date.
        /// </summary>
        public static string ConsentValidFromBeforeValidTo {
            get {
                return ResourceManager.GetString("ConsentValidFromBeforeValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent valid from.
        /// </summary>
        public static string ConsentValidFromLabel {
            get {
                return ResourceManager.GetString("ConsentValidFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent valid from date is required.
        /// </summary>
        public static string ConsentValidFromRequired {
            get {
                return ResourceManager.GetString("ConsentValidFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent valid to.
        /// </summary>
        public static string ConsentValidToLabel {
            get {
                return ResourceManager.GetString("ConsentValidToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consent valid to date is required.
        /// </summary>
        public static string ConsentValidToRequired {
            get {
                return ResourceManager.GetString("ConsentValidToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string DecisionLabel {
            get {
                return ResourceManager.GetString("DecisionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ObjectedDateLabel {
            get {
                return ResourceManager.GetString("ObjectedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date the objection was made.
        /// </summary>
        public static string ObjectedDateRequired {
            get {
                return ResourceManager.GetString("ObjectedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons for withdrawal of consent.
        /// </summary>
        public static string ReasonConsentWithdrawalLabel {
            get {
                return ResourceManager.GetString("ReasonConsentWithdrawalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason consent is being withdrawn is required.
        /// </summary>
        public static string ReasonConsentWithdrawnRequired {
            get {
                return ResourceManager.GetString("ReasonConsentWithdrawnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons for objection.
        /// </summary>
        public static string ReasonObjectedLabel {
            get {
                return ResourceManager.GetString("ReasonObjectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason for objection is required.
        /// </summary>
        public static string ReasonObjectedRequired {
            get {
                return ResourceManager.GetString("ReasonObjectedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons for withdrawal.
        /// </summary>
        public static string ReasonWithdrawnLabel {
            get {
                return ResourceManager.GetString("ReasonWithdrawnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason the notification is being withdrawn is required.
        /// </summary>
        public static string ReasonWithdrawnRequired {
            get {
                return ResourceManager.GetString("ReasonWithdrawnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string WithdrawnDateLabel {
            get {
                return ResourceManager.GetString("WithdrawnDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date the notificaiton was withdrawn.
        /// </summary>
        public static string WithdrawnDateRequired {
            get {
                return ResourceManager.GetString("WithdrawnDateRequired", resourceCulture);
            }
        }
    }
}
